/*
 * SPDX-FileCopyrightText: 2025 Pagefault Games
 * SPDX-FileContributor: Sisyphus
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { existsSync, constants as fsConstants } from "node:fs";
import { access, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "../..");
const MANIFEST_PATH = resolve(ROOT, "src/data/elite-redux/er-sprite-manifest.ts");
const ASSETS_DIR = resolve(ROOT, "assets/images/pokemon/elite-redux");
const REPORT_PATH = resolve(ROOT, "docs/plans/elite-redux-known-missing-sprites.md");

/**
 * Extract the ER_SPRITE_MANIFEST array from the emitted TS file.
 * The builder embeds the entries as a JSON.stringify body — we slice it out
 * and JSON.parse it so we don't have to spin up the TS toolchain.
 * @returns {Promise<Array<{ speciesId: number, speciesConst: string, slug: string, paths: { front: string, back: string, icon: string, animFront: string, footprint: string, shinyFront: string, shinyBack: string, shinyPlusFront: string, shinyPlusBack: string, shinyUltraFront: string, shinyUltraBack: string } }>>}
 */
export async function loadManifest(manifestPath = MANIFEST_PATH) {
  const text = await readFile(manifestPath, "utf8");
  const m = /export const ER_SPRITE_MANIFEST[^=]*=\s*(\[[\s\S]*?\])\s*as const;/.exec(text);
  if (!m) {
    throw new Error(`Couldn't parse ER_SPRITE_MANIFEST from ${manifestPath}`);
  }
  return JSON.parse(m[1]);
}

/** @param {string} path */
async function fileExists(path) {
  try {
    await access(path, fsConstants.R_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Audit a manifest against on-disk sprites. Pure function — the I/O probe is injected.
 * @param {ReturnType<typeof loadManifest> extends Promise<infer T> ? T : never} manifest
 * @param {(absPath: string) => Promise<boolean>} probe
 * @param {string} root
 */
export async function auditManifest(manifest, probe, root) {
  /** @type {Array<{ slug: string, speciesConst: string, speciesId: number, missingPaths: string[] }>} */
  const missing = [];
  let totalExpected = 0;
  let totalPresent = 0;

  for (const entry of manifest) {
    const paths = [
      entry.paths.front,
      entry.paths.back,
      entry.paths.icon,
      entry.paths.animFront,
      entry.paths.footprint,
      entry.paths.shinyFront,
      entry.paths.shinyBack,
      entry.paths.shinyPlusFront,
      entry.paths.shinyPlusBack,
      entry.paths.shinyUltraFront,
      entry.paths.shinyUltraBack,
    ];
    /** @type {string[]} */
    const missingForEntry = [];
    for (const relPath of paths) {
      totalExpected++;
      const absPath = resolve(root, relPath);
      if (await probe(absPath)) {
        totalPresent++;
      } else {
        missingForEntry.push(relPath);
      }
    }
    if (missingForEntry.length > 0) {
      missing.push({
        slug: entry.slug,
        speciesConst: entry.speciesConst,
        speciesId: entry.speciesId,
        missingPaths: missingForEntry,
      });
    }
  }

  return { missing, totalExpected, totalPresent };
}

/** Per-species variant count tracked by the audit. Keep in sync with auditManifest above. */
const VARIANTS_PER_SPECIES = 11;

/**
 * Compose the markdown report body.
 * @param {Awaited<ReturnType<typeof auditManifest>>} result
 */
export function renderReport(result) {
  const { missing, totalExpected, totalPresent } = result;
  const allMissing = missing.filter(m => m.missingPaths.length === VARIANTS_PER_SPECIES);
  const partial = missing.filter(m => m.missingPaths.length < VARIANTS_PER_SPECIES);
  const coveragePct = totalExpected > 0 ? ((totalPresent / totalExpected) * 100).toFixed(2) : "0.00";

  let body = "# Elite Redux — Known Missing Sprites\n\n";
  body += `> Generated by \`pnpm run er:audit-sprites\`. Last run: ${new Date().toISOString()}\n\n`;
  body += "## Summary\n\n";
  body += `- Total sprites expected: **${totalExpected}**\n`;
  body += `- Sprites present: **${totalPresent}** (${coveragePct}%)\n`;
  body += `- Species missing all ${VARIANTS_PER_SPECIES} variants: **${allMissing.length}**\n`;
  body += `- Species partially missing: **${partial.length}**\n`;
  body += `- Total species with at least one missing variant: **${missing.length}**\n\n`;

  body += "## Remediation\n\n";
  body += "Resolve each missing-sprite gap by one of:\n";
  body += "1. Re-running `pnpm run er:fetch-sprites` (some sprites may have been renamed upstream)\n";
  body += "2. Sourcing the sprite from the upstream Elite-Redux/eliteredux repo under a different filename\n";
  body += "3. Hand-creating a placeholder PNG\n";
  body += '4. Documenting the species as "shipped without sprites" in this file\'s "Accepted Gaps" section\n\n';

  if (allMissing.length > 0) {
    body += `## Completely Missing (${allMissing.length} species)\n\n`;
    body += "These species have no sprites at all. Likely candidates for sourcing from upstream or placeholders.\n\n";
    body += "| slug | speciesConst |\n|---|---|\n";
    for (const m of allMissing.slice(0, 50)) {
      body += `| \`${m.slug}\` | \`${m.speciesConst}\` |\n`;
    }
    if (allMissing.length > 50) {
      body += `\n_(${allMissing.length - 50} more — see audit output)_\n`;
    }
  }

  if (partial.length > 0) {
    body += `\n## Partially Missing (${partial.length} species)\n\n`;
    body += "These species have SOME sprites; only specific variants (e.g., shiny-back) are absent.\n\n";
    body += "| slug | missing variants |\n|---|---|\n";
    for (const m of partial.slice(0, 50)) {
      const variants = m.missingPaths
        .map(p => {
          const segs = p.split("/");
          return `${segs.at(-2)}/${segs.at(-1)}`;
        })
        .join(", ");
      body += `| \`${m.slug}\` | ${variants} |\n`;
    }
    if (partial.length > 50) {
      body += `\n_(${partial.length - 50} more)_\n`;
    }
  }

  body += "\n## Accepted Gaps\n\n";
  body += "Gaps below are tracked here per the Phase B plan, with remediation owned by Phase C asset work.\n\n";
  body += "### ER-custom species without upstream sprites\n\n";
  body += "**Status:** structural — the upstream `Elite-Redux/eliteredux` repo only ships PNGs for vanilla\n";
  body += "Gen1-9 Pokémon. ER-original species (`*_REDUX`, custom megas) typically have no source PNG.\n\n";
  body += "**Remediation (Phase C):** source sprites from the ER community (Discord asset packs, fan ports),\n";
  body += "hand-create placeholders, or render shiny variants from palette files. Track individual sprite\n";
  body += "additions here as they land.\n\n";
  body += "### Shiny variants (generated from palette files)\n\n";
  body += "**Status:** the manifest expects 6 shiny PNGs per species — 3 tiers (regular/+/++) × 2 views\n";
  body += "(front/back). They are GENERATED by `pnpm run er:render-shinies` from the upstream `shiny.pal`\n";
  body += "JASC palette file: tier 1 is the exact palette swap, tier 2/3 are derived by hue-rotating the\n";
  body += "shiny palette by 120°/240° to give the rare/legendary tiers a distinct dominant hue.\n";
  body += "Re-run the renderer (it's idempotent) if the audit reports missing `shiny*.png` entries.\n\n";
  body += "### anim_front + footprint partial coverage\n\n";
  body += "**Status:** ~185 vanilla species have front+back+icon but no animated front or footprint frames.\n";
  body += "Acceptable for Phase B — these are optional visual flourishes (footprint is dex-only, anim_front\n";
  body += "falls back to static front). Phase C should fill where feasible.\n";

  return body;
}

async function main() {
  if (!existsSync(ASSETS_DIR)) {
    console.error(`[er:audit-sprites] Sprite directory missing: ${ASSETS_DIR}`);
    console.error("[er:audit-sprites] Run `pnpm run er:fetch-sprites` first.");
    process.exit(2);
  }

  const manifest = await loadManifest();
  console.log(`[er:audit-sprites] auditing ${manifest.length} manifest entries against ${ASSETS_DIR}`);

  const result = await auditManifest(manifest, fileExists, ROOT);
  const { missing, totalExpected, totalPresent } = result;

  const coveragePct = totalExpected > 0 ? ((totalPresent / totalExpected) * 100).toFixed(2) : "0.00";
  console.log(`[er:audit-sprites] ${totalPresent} / ${totalExpected} sprites present (${coveragePct}%)`);
  console.log(`[er:audit-sprites] ${missing.length} species missing one or more variants`);

  const allMissing = missing.filter(m => m.missingPaths.length === VARIANTS_PER_SPECIES);
  const partial = missing.filter(m => m.missingPaths.length < VARIANTS_PER_SPECIES);
  console.log(`[er:audit-sprites]   ${allMissing.length} species completely missing`);
  console.log(`[er:audit-sprites]   ${partial.length} species partially missing`);

  await writeFile(REPORT_PATH, renderReport(result), "utf8");

  const exitCode = missing.length === 0 ? 0 : 1;
  if (exitCode === 0) {
    console.log("[er:audit-sprites] All sprites present.");
  } else {
    console.warn(`[er:audit-sprites] Audit FAILED — ${missing.length} species have missing sprites.`);
    console.warn(`[er:audit-sprites] See ${REPORT_PATH} for details.`);
  }
  process.exit(exitCode);
}

// Only run main() when invoked as a script (not when imported by tests).
const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main().catch(err => {
    console.error(err);
    process.exit(3);
  });
}
