[package]
name = "er-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
er-render-model = { path = "../er-render-model" }
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
