import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,lstatSync} from 'node:fs';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
assert.equal(process.argv.length,4);const dir=process.argv[2],hash=b=>createHash('sha256').update(b).digest('hex');
const shape=(v,keys)=>assert.deepEqual(Object.keys(v).sort(),[...keys].sort());const int=(n,a,b)=>assert(Number.isSafeInteger(n)&&n>=a&&n<=b);
const receiptPath=join(dir,'digest-two.json'),receiptStat=lstatSync(receiptPath);assert(receiptStat.isFile()&&!receiptStat.isSymbolicLink()&&receiptStat.size<=4096);const receiptRaw=readFileSync(receiptPath),receipt=JSON.parse(receiptRaw);assert.equal(JSON.stringify(receipt)+'\n',receiptRaw.toString());shape(receipt,['schema','source','parts']);assert.equal(receipt.schema,1);assert.equal(receipt.source,'399d5d368f0b5642ebf8f45bd8a5e73350fa4de7');assert(Array.isArray(receipt.parts)&&receipt.parts.length>=14&&receipt.parts.length<=59);
const names=receipt.parts.map(row=>row[0]);assert.deepEqual(names.slice(0,14),['species','moves','forms','abilities-meta','gender','form-flags','ability-slots','form-types','form-stats','level-two-forms','level-two-meta','level-two-movegen','level-two-abilities','movegen-stage']);for(const section of ['rows','functions','shapes']){const pages=names.filter(name=>name.startsWith(`abilities-${section}-`));assert(pages.length>0&&pages.length<=16);assert.deepEqual(pages,pages.map((_,i)=>`abilities-${section}-${String(i).padStart(2,'0')}`));}assert.equal(new Set(names).size,names.length);assert.equal(names.length,14+['rows','functions','shapes'].reduce((n,section)=>n+names.filter(name=>name.startsWith(`abilities-${section}-`)).length,0));
const pieces={},facts={};for(const row of receipt.parts){assert(Array.isArray(row)&&row.length===3);const [name,length,digest]=row,cap=['gender','form-flags','movegen-stage'].includes(name)?4096:['ability-slots','form-types','level-two-forms','level-two-meta','level-two-movegen','level-two-abilities'].includes(name)?8192:['species','moves'].includes(name)?32768:16384;int(length,1,cap);assert(typeof digest==='string'&&/^[a-f0-9]{64}$/.test(digest));const p=join(dir,`${name}-one.json`),s=lstatSync(p);assert(s.isFile()&&!s.isSymbolicLink()&&s.size===length);const raw=readFileSync(p);assert.equal(hash(raw),digest);const value=JSON.parse(raw);assert.equal(JSON.stringify(value)+'\n',raw.toString());pieces[name]=value;facts[name]={bytes:length,sha256:digest};}
const stage=pieces['movegen-stage'];shape(stage,['schema','source','entry','species','level','form','ability','stats','types','initial','filtered','adjusted','weighted','moves']);assert.equal(stage.schema,1);assert.equal(stage.source,receipt.source);assert.equal(stage.entry,'direct queued NextEncounterPhase, Ace Town day wave two');assert.equal(stage.species,263);assert.equal(stage.level,2);int(stage.form,0,19);int(stage.ability,1,10000);assert(Array.isArray(stage.stats)&&stage.stats.length===6);for(const n of stage.stats)int(n,1,10000);assert(Array.isArray(stage.types)&&stage.types.length>=1&&stage.types.length<=3);for(const n of stage.types)int(n,0,18);assert(Array.isArray(stage.moves)&&stage.moves.length>=1&&stage.moves.length<=4);for(const n of stage.moves)int(n,1,100000);for(const key of ['initial','filtered','adjusted','weighted']){assert(Array.isArray(stage[key])&&stage[key].length>0&&stage[key].length<=512);for(const row of stage[key]){assert(Array.isArray(row)&&row.length===2);int(row[0],1,100000);assert(typeof row[1]==='number'&&Number.isFinite(row[1])&&row[1]>=0&&row[1]<=1e9);}}assert.deepEqual(stage.filtered.map(row=>row[0]),stage.adjusted.map(row=>row[0]));assert.deepEqual(stage.adjusted.map(row=>row[0]),stage.weighted.map(row=>row[0]));for(let i=0;i<stage.weighted.length;i++)assert.equal(stage.weighted[i][1],Math.ceil(Math.pow(stage.adjusted[i][1],1.6)*100));
const abilities={...pieces['abilities-meta']};shape(abilities,['schema','source','runtime_slots']);for(const section of ['rows','functions','shapes'])abilities[section]=names.filter(name=>name.startsWith(`abilities-${section}-`)).flatMap((name,index)=>{const page=pieces[name];shape(page,['schema','section','index','items']);assert.equal(page.schema,1);assert.equal(page.section,section);assert.equal(page.index,index);assert(Array.isArray(page.items)&&page.items.length>0&&page.items.length<=512);return page.items;});const inputs={species:pieces.species,moves:pieces.moves,forms:pieces.forms,abilities,gender:pieces.gender,formFlags:pieces['form-flags'],abilitySlots:pieces['ability-slots'],formTypes:pieces['form-types'],formStats:pieces['form-stats'],levelTwoForms:pieces['level-two-forms'],levelTwoMeta:pieces['level-two-meta'],levelTwoMovegen:pieces['level-two-movegen'],levelTwoAbilities:pieces['level-two-abilities']};
function unpackColumns(table,width){
 assert(Array.isArray(table)&&table.length===2);const [count,columns]=table;int(count,1,512);assert(Array.isArray(columns)&&columns.length===width);const rows=Array.from({length:count},()=>[]);
 for(const column of columns){assert(Array.isArray(column)&&(column.length===2||column.length===3));const values=column[0];assert(Array.isArray(values)&&values.length>0&&values.length<=count);assert.equal(new Set(values.map(value=>JSON.stringify(value))).size,values.length);let indices;
  if(column.length===2){indices=column[1];assert(Array.isArray(indices)&&indices.length===count);}else{const base=column[1];int(base,0,values.length-1);indices=Array(count).fill(base);assert(Array.isArray(column[2])&&column[2].length<=count);let prior=-1;for(const entry of column[2]){assert(Array.isArray(entry)&&entry.length===2);int(entry[0],0,count-1);assert(entry[0]>prior);prior=entry[0];int(entry[1],0,values.length-1);assert.notEqual(entry[1],base);indices[entry[0]]=entry[1];}}
  const seen=new Set();for(let i=0;i<count;i++){const id=indices[i];int(id,0,values.length-1);if(!seen.has(id)){assert.equal(id,seen.size);seen.add(id);}rows[i].push(values[id]);}assert.equal(seen.size,values.length);
 }return rows;
}
function unpackSpecies(part,forms){
 shape(part,['schema','source','roots','tiers','level_cap','wild_kind','context','rows_columns','level_columns','level_rows']);assert.equal(part.schema,4);
 shape(forms,['schema','source','form_columns','functions','shapes']);assert.equal(forms.schema,1);assert.equal(forms.source,part.source);
 assert(Array.isArray(part.level_rows)&&part.level_rows.length<=512*13);assert.equal(new Set(part.level_rows.map(row=>JSON.stringify(row))).size,part.level_rows.length);for(const row of part.level_rows){assert(Array.isArray(row)&&row.length===2);int(row[0],-2,10);int(row[1],0,100000);}
 const usedLevels=new Set();const levels=unpackColumns(part.level_columns,3).map(([refs,count,digest])=>{assert(Array.isArray(refs)&&refs.length<=512);assert(typeof digest==='string'&&/^[A-Za-z0-9_-]{43}$/.test(digest));const bytes=Buffer.from(digest,'base64url');assert.equal(bytes.length,32);assert.equal(bytes.toString('base64url'),digest);return [refs.map(id=>{int(id,0,part.level_rows.length-1);if(!usedLevels.has(id)){assert.equal(id,usedLevels.size);usedLevels.add(id);}return part.level_rows[id];}),count,bytes.toString('hex')];});assert.equal(usedLevels.size,part.level_rows.length);
 const rows=unpackColumns(part.rows_columns,10).map(row=>{assert(Array.isArray(row[6])&&row[6].length>0&&row[6].length<=20);const result=[...row];result[6]=row[6].map((binding,index)=>{assert(Array.isArray(binding)&&binding.length===2);return [index,...binding];});return result;});
 const {rows_columns,level_columns,level_rows,...metadata}=part;return {...metadata,schema:2,functions:forms.functions,shapes:forms.shapes,rows,form_data:unpackColumns(forms.form_columns,6),level_sets:levels};
}
const packedSpecies=inputs.species,packedForms=inputs.forms;
const packedMutations=[s=>s.unexpected=true,s=>s.rows_columns[0]=0,s=>s.rows_columns[1][0][0].push(s.rows_columns[1][0][0][0]),s=>s.rows_columns[1][0]=[s.rows_columns[1][0][0],0,[[s.rows_columns[0],0]]],s=>s.level_columns[1][2][0][0]='A'.repeat(42),s=>s.level_rows.push(s.level_rows[0])];for(const mutate of packedMutations){const s=structuredClone(packedSpecies);mutate(s);assert.throws(()=>unpackSpecies(s,packedForms));}
const formsMutations=[f=>f.source='other',f=>f.form_columns[0]=0,f=>f.form_columns[1][0][0].push(f.form_columns[1][0][0][0])];for(const mutate of formsMutations){const f=structuredClone(packedForms);mutate(f);assert.throws(()=>unpackSpecies(packedSpecies,f));}
inputs.species=unpackSpecies(packedSpecies,packedForms);delete inputs.forms;
function decode(value,part,depth=0){
 const {functions,shapes}=part;
 assert(depth<=12);if(value===null||typeof value==='boolean'||typeof value==='string'){if(typeof value==='string')assert(value.length<=1024);return value;}
 if(typeof value==='number'){assert(Number.isFinite(value));return value;}
 if(Array.isArray(value)){assert(value.length<=512);return value.map(v=>decode(v,part,depth+1));}
 assert(typeof value==='object');const keys=Object.keys(value);
 if(keys.length===1&&keys[0]==='m'){assert(Array.isArray(value.m)&&value.m.length<=512);return new Map(value.m.map(r=>{assert(Array.isArray(r)&&r.length===2);return r.map(x=>decode(x,part,depth+1));}));}
 if(keys.length===1&&keys[0]==='s'){assert(Array.isArray(value.s)&&value.s.length<=512);return new Set(value.s.map(v=>decode(v,part,depth+1)));}
 if(keys.length===1&&keys[0]==='u'){assert.equal(value.u,1);return undefined;}
 if(keys.length===1&&keys[0]==='n'){assert(['NaN','Infinity','-Infinity'].includes(value.n));return Number(value.n);}
 if(keys.length===1&&keys[0]==='f'){int(value.f,0,functions.length-1);return {sourceFunction:value.f};}
 shape(value,['o']);assert(Array.isArray(value.o)&&value.o.length===2);const [index,values]=value.o;int(index,0,shapes.length-1);const fieldKeys=shapes[index][1];assert(Array.isArray(values)&&values.length===fieldKeys.length);const out=Object.create(null);for(let i=0;i<fieldKeys.length;i++){if(shapes[index][0]==='NullifyFirstNHitsAbAttr'&&fieldKeys[i]==='usage'){assert.deepEqual(part.runtime_slots,[0,0]);assert.deepEqual(values[i],{w:0});out[fieldKeys[i]]={freshConstructorRuntimeSlot:'NullifyFirstNHitsAbAttr.usage'};}else out[fieldKeys[i]]=decode(values[i],part,depth+1);}return out;

}
const countPath=join(dir,'form-counts.json'),countStat=lstatSync(countPath);assert(countStat.isFile()&&!countStat.isSymbolicLink()&&countStat.size<=4096);const countRaw=readFileSync(countPath),countReceipt=JSON.parse(countRaw);shape(countReceipt,['source','scope','roots','visited','max_forms','counts']);assert.equal(countReceipt.source,'399d5d368f0b5642ebf8f45bd8a5e73350fa4de7');assert.equal(countReceipt.scope,'complete visited Town evolution graph source form counts before payload extraction');assert.equal(countReceipt.roots,54);assert.equal(countReceipt.max_forms,20);
function validate(d){
 for(const part of [d.species,d.moves,d.abilities]){assert.equal(part.schema,2);assert.equal(part.source,'399d5d368f0b5642ebf8f45bd8a5e73350fa4de7');assert(Array.isArray(part.functions)&&part.functions.length<=512);assert(Array.isArray(part.shapes)&&part.shapes.length<=512);assert.equal(new Set(part.shapes.map(s=>JSON.stringify(s))).size,part.shapes.length);for(const row of part.shapes){assert(Array.isArray(row)&&row.length===2);assert(row[0]===null||(typeof row[0]==='string'&&row[0].length<=128));assert(Array.isArray(row[1])&&row[1].length<=128&&row[1].every(k=>typeof k==='string'));assert.equal(new Set(row[1]).size,row[1].length);}for(const f of part.functions){assert(Array.isArray(f)&&f.length===2&&/^[a-f0-9]{64}$/.test(f[0]));int(f[1],1,65536);}}
 const s=d.species;shape(s,['schema','source','roots','tiers','level_cap','wild_kind','context','rows','functions','shapes','form_data','level_sets']);assert.equal(s.level_cap,10);assert.equal(s.wild_kind,2);
 const abilitySlots=d.abilitySlots;shape(abilitySlots,['schema','source','rows']);assert.equal(abilitySlots.schema,1);assert.equal(abilitySlots.source,s.source);assert(Array.isArray(abilitySlots.rows));assert.deepEqual(abilitySlots.rows.map(row=>row[0]),s.rows.map(row=>row[0]));for(const [index,row] of abilitySlots.rows.entries()){assert(Array.isArray(row)&&row.length===2);const bindings=s.rows[index][6];assert(Array.isArray(row[1])&&row[1].length===bindings.length);for(const [formIndex,active] of row[1].entries())assert.deepEqual(active,s.form_data[bindings[formIndex][2]][3]);}
 const formTypes=d.formTypes;shape(formTypes,['schema','source','rows']);assert.equal(formTypes.schema,1);assert.equal(formTypes.source,s.source);assert(Array.isArray(formTypes.rows));assert.deepEqual(formTypes.rows.map(row=>row[0]),s.rows.map(row=>row[0]));for(const [index,row] of formTypes.rows.entries()){assert(Array.isArray(row)&&row.length===2);const bindings=s.rows[index][6];assert(Array.isArray(row[1])&&row[1].length===bindings.length);for(const [formIndex,typing] of row[1].entries()){assert(Array.isArray(typing)&&typing.length===3);const source=s.form_data[bindings[formIndex][2]];assert.deepEqual(typing.slice(0,2),source.slice(0,2));assert(Array.isArray(typing[2])&&typing[2].length<=6);const seen=new Set(typing.slice(0,2));for(const id of typing[2]){int(id,0,32);assert(!seen.has(id));seen.add(id);}}}
 const formStats=d.formStats;shape(formStats,['schema','source','rows']);assert.equal(formStats.schema,1);assert.equal(formStats.source,s.source);assert(Array.isArray(formStats.rows));assert.deepEqual(formStats.rows.map(row=>row[0]),s.rows.map(row=>row[0]));for(const [index,row] of formStats.rows.entries()){assert(Array.isArray(row)&&row.length===2);const bindings=s.rows[index][6];assert(Array.isArray(row[1])&&row[1].length===bindings.length);for(const [formIndex,stats] of row[1].entries()){assert(Array.isArray(stats)&&stats.length===6);stats.forEach(value=>int(value,0,10000));assert.deepEqual(stats,s.form_data[bindings[formIndex][2]][2]);}}
 const levelTwoForms=d.levelTwoForms;shape(levelTwoForms,['schema','source','rows']);assert.equal(levelTwoForms.schema,1);assert.equal(levelTwoForms.source,s.source);const effectiveRoots=[...new Set(s.roots.map(id=>id===266?265:id))];assert.deepEqual(levelTwoForms.rows.map(row=>row[0]),effectiveRoots);const nodesById=new Map(s.rows.map(row=>[row[0],row]));for(const [id,formRows] of levelTwoForms.rows){const node=nodesById.get(id);assert(node);assert(Array.isArray(formRows)&&formRows.length===node[6].length);for(const [index,rows] of formRows.entries()){assert(Array.isArray(rows)&&rows.length<=512);const form=s.form_data[node[6][index][2]],expected=s.level_sets[form[5]][0].filter(row=>row[0]<=2);assert.deepEqual(rows,expected);}}
 const formFlags=d.formFlags;shape(formFlags,['schema','source','rows']);assert.equal(formFlags.schema,1);assert.equal(formFlags.source,s.source);assert(Array.isArray(formFlags.rows));assert.deepEqual(formFlags.rows.map(row=>row[0]),s.rows.map(row=>row[0]));for(const [index,row] of formFlags.rows.entries()){assert(Array.isArray(row)&&row.length===2);int(row[1],0,2**s.rows[index][6].length-1);}
 const gender=d.gender;shape(gender,['schema','source','rows']);assert.equal(gender.schema,1);assert.equal(gender.source,s.source);assert(Array.isArray(gender.rows));assert.deepEqual(gender.rows.map(row=>row[0]),s.rows.map(row=>row[0]));for(const row of gender.rows){assert(Array.isArray(row)&&row.length===2);const percent=row[1];assert(percent===null||(typeof percent==='number'&&Number.isFinite(percent)&&percent>=0&&percent<=100));}
 shape(s.context,['wave','biome','difficulty','time','luck','forced','regional']);assert.equal(s.context.wave,2);assert.equal(s.context.biome,0);assert(['ace','youngster','elite','hell','mystery'].includes(s.context.difficulty));int(s.context.time,0,12);assert(Number.isFinite(s.context.luck)&&s.context.luck>=0&&s.context.luck<=100);if(s.context.forced!==null)int(s.context.forced,0,12);if(s.context.regional!==null)assert.equal(typeof s.context.regional,'boolean');
 assert(Array.isArray(s.tiers)&&s.tiers.length>0&&s.tiers.length<=12);let last=-1;for(const r of s.tiers){assert(Array.isArray(r)&&r.length===2);int(r[0],0,12);assert(r[0]>last);last=r[0];assert(Array.isArray(r[1])&&r[1].length<=128);for(const id of r[1])int(id,1,100000);}
 assert.deepEqual(s.roots,[...new Set(s.tiers.flatMap(r=>r[1]))]);assert.equal(s.roots.length,54);assert(Array.isArray(s.rows)&&s.rows.length>=54&&s.rows.length<=256);
 assert(Array.isArray(s.form_data)&&s.form_data.length>0&&s.form_data.length<=512);assert(Array.isArray(s.level_sets)&&s.level_sets.length>0&&s.level_sets.length<=512);
 assert.equal(new Set(s.form_data.map(r=>JSON.stringify(r))).size,s.form_data.length);assert.equal(new Set(s.level_sets.map(r=>JSON.stringify(r))).size,s.level_sets.length);
 const usedForms=new Set(),usedLevels=new Set();
 const nodes=new Map(),moveIds=[],abilityIds=[];const add=(list,id)=>{int(id,0,100000);if(!list.includes(id))list.push(id);};
 for(const n of s.rows){assert(Array.isArray(n)&&n.length===10);const [id,evoOwn,e,preOwn,p,pl,forms,sig,sigOwn,incoming]=n;int(id,1,100000);assert(!nodes.has(id));for(const flag of [evoOwn,preOwn,sigOwn])assert.equal(typeof flag,'boolean');const evos=decode(e,s),pre=decode(p,s),preLevels=decode(pl,s),signature=decode(sig,s);assert(Array.isArray(evos)&&evos.length<=128);if(!evoOwn)assert.equal(evos.length,0);if(preOwn)int(pre,1,100000);else assert.equal(pre,undefined);if(!sigOwn)assert.equal(signature,undefined);else if(signature!==undefined){assert(typeof signature==='number'||Array.isArray(signature));const ids=Array.isArray(signature)?signature:[signature];assert(ids.length<=32);for(const x of ids)int(x,1,100000);}
 assert(Array.isArray(preLevels)&&preLevels.length<=128);for(const row of preLevels){assert(Array.isArray(row)&&row.length>=2&&row.length<=3);int(row[0],1,100000);}
 assert(Array.isArray(forms)&&forms.length>0&&forms.length<=20);for(const [i,binding] of forms.entries()){
  assert(Array.isArray(binding)&&binding.length===3);assert.equal(binding[0],i);assert(binding[1]===null||typeof binding[1]==='string');int(binding[2],0,s.form_data.length-1);usedForms.add(binding[2]);const f=s.form_data[binding[2]];assert(Array.isArray(f)&&f.length===6);
  int(f[0],0,32);if(f[1]!==null)int(f[1],0,32);assert(Array.isArray(f[2])&&f[2].length===6);f[2].forEach(x=>int(x,1,10000));assert(Array.isArray(f[3])&&f[3].length>=2&&f[3].length<=3);assert(Array.isArray(f[4])&&f[4].length===3);[...f[3],...f[4]].forEach(x=>add(abilityIds,x));int(f[5],0,s.level_sets.length-1);usedLevels.add(f[5]);const levels=s.level_sets[f[5]];assert(Array.isArray(levels)&&levels.length===3);assert(Array.isArray(levels[0])&&levels[0].length<=512);for(const row of levels[0]){assert(Array.isArray(row)&&row.length===2);int(row[0],-2,10);add(moveIds,row[1]);}int(levels[1],levels[0].length,512);assert(/^[a-f0-9]{64}$/.test(levels[2]));}
 assert(Array.isArray(incoming)&&incoming.length<=128);for(const row of incoming){assert(Array.isArray(row)&&row.length===2);int(row[0],1,100000);int(row[1],0,127);}
 nodes.set(id,{evos,preOwn,pre,preLevels,incoming});}
 assert.equal(usedForms.size,s.form_data.length);assert.equal(usedLevels.size,s.level_sets.length);
 for(const [id,node] of nodes){const incoming=[...nodes].sort(([a],[b])=>a-b).flatMap(([parent,n])=>n.evos.flatMap((e,index)=>e.speciesId===id?[[parent,index]]:[]));assert.deepEqual(node.incoming,incoming);}
 const seen=new Set(),queue=s.roots.map(id=>[id,0]);for(let i=0;i<queue.length;i++){const [id,depth]=queue[i];if(seen.has(id))continue;int(depth,0,32);assert(nodes.has(id));seen.add(id);const n=nodes.get(id);for(const e of n.evos){int(e.speciesId,1,100000);queue.push([e.speciesId,depth+1]);}for(const row of n.preLevels)queue.push([row[0],depth+1]);if(n.preOwn)queue.push([n.pre,depth+1]);for(const [parent,index] of n.incoming){assert(nodes.has(parent)&&nodes.get(parent).evos[index]?.speciesId===id);queue.push([parent,depth+1]);}}assert.deepEqual([...nodes.keys()],[...seen]);
 const m=d.moves;shape(m,['schema','source','rows','functions','shapes','tuning']);assert.deepEqual(m.rows.map(r=>r[0]),moveIds);assert(m.rows.length<=512);assert(m.tuning.length===7);for(const n of m.tuning)assert(Number.isFinite(n)&&n>0&&n<=1000);
 const levelTwoMeta=d.levelTwoMeta;shape(levelTwoMeta,['schema','source','rows']);assert.equal(levelTwoMeta.schema,1);assert.equal(levelTwoMeta.source,s.source);const selectedMoves=[...new Set(levelTwoForms.rows.flatMap(([,forms])=>forms.flatMap(rows=>rows.map(row=>row[1]))))];assert.deepEqual(levelTwoMeta.rows.map(row=>row[0]),selectedMoves);const moveById=new Map(m.rows.map(row=>[row[0],row]));for(const row of levelTwoMeta.rows){assert(Array.isArray(row)&&row.length===7);const source=moveById.get(row[0]);assert(source&&source[1]===true);assert.deepEqual(row,[source[0],...source.slice(2,8)]);}
 const movegen=d.levelTwoMovegen;shape(movegen,['schema','source','rows']);assert.equal(movegen.schema,1);assert.equal(movegen.source,s.source);assert.deepEqual(movegen.rows.map(row=>row[0]),selectedMoves);for(const row of movegen.rows){assert(Array.isArray(row)&&row.length===3);int(row[0],1,100000);assert(typeof row[1]==='number'&&Number.isFinite(row[1])&&row[1]>=0&&row[1]<=10000);int(row[2],0,255);}
 for(const row of m.rows){assert(Array.isArray(row));assert.equal(typeof row[1],'boolean');if(!row[1]){assert.equal(row.length,2);continue;}assert.equal(row.length,13);int(row[2],0,2);int(row[3],0,32);assert(Number.isFinite(row[4]));assert(Number.isFinite(row[5]));for(const i of [6,7,11,12])assert.equal(typeof row[i],'boolean');assert(typeof row[8]==='string');assert(Array.isArray(decode(row[9],m)));decode(row[10],m);}
 const a=d.abilities;shape(a,['schema','source','rows','functions','shapes','runtime_slots']);assert.deepEqual(a.runtime_slots,[0,0]);assert.deepEqual(a.rows.map(r=>r[0]),abilityIds);assert(a.rows.length<=512);for(const row of a.rows){assert(row.length===2);assert(Array.isArray(decode(row[1],a)));}
 const profiles=d.levelTwoAbilities;shape(profiles,['schema','source','rows','movegen_modifiers']);assert.equal(profiles.schema,1);assert.equal(profiles.source,s.source);assert.deepEqual(profiles.rows.map(row=>row[0]),effectiveRoots);for(const [id,forms] of profiles.rows){const node=nodesById.get(id);assert(node);assert.equal(forms.length,node[6].length);for(const [index,profile] of forms.entries()){assert(Array.isArray(profile)&&profile.length===2);const source=s.form_data[node[6][index][2]];assert.deepEqual(profile,[source[3],source[4]]);}}const modifiers=a.rows.filter(([,attrs])=>attrs.some(attr=>{assert(Array.isArray(attr.o)&&attr.o.length===2);return /AiMovegenMoveStatsAbAttr$|VariableMovePowerAbAttr$/.test(a.shapes[attr.o[0]][0]);})).map(row=>row[0]);assert.deepEqual(profiles.movegen_modifiers,modifiers);
 assert.deepEqual(countReceipt.counts,s.rows.map(n=>[n[0],n[6].length]));assert.equal(countReceipt.visited,s.rows.length);assert.equal(Math.max(...countReceipt.counts.map(r=>r[1])),countReceipt.max_forms);
 const eligibility=[];for(const id of s.roots)for(let level=1;level<=10;level++){const n=nodes.get(id);let forced=null;if(n.preOwn)for(let i=n.preLevels.length-1;i>=0;i--){const [pre,req,thresholds]=n.preLevels[i],threshold=thresholds?.[s.wild_kind]??req;if(level<(req===1?threshold:Math.min(req,threshold))){forced=pre;break;}}const eligible=forced===null?n.evos.flatMap(e=>{const threshold=Math.max(e.level,e.evoLevelThreshold?.[s.wild_kind]??0);return level<e.level||level<threshold||!(threshold>0)?[]:[[threshold,e.speciesId]];}):[];eligibility.push([id,level,forced,eligible]);}
 return {roots:s.roots.length,species:s.rows.length,moves:m.rows.length,abilities:a.rows.length,gender_rows:gender.rows.length,form_flag_rows:formFlags.rows.length,ability_slot_rows:abilitySlots.rows.length,form_type_rows:formTypes.rows.length,form_stat_rows:formStats.rows.length,level_two_form_rows:levelTwoForms.rows.length,level_two_move_rows:levelTwoMeta.rows.length,eligibility_sha256:hash(JSON.stringify(eligibility)),level2_forced:eligibility.filter(r=>r[1]===2&&r[2]!==null).map(r=>[r[0],r[2]]),level2_upward_roots:eligibility.filter(r=>r[1]===2&&r[3].length>0).map(r=>r[0])};
}
const result=validate(inputs);const ownUndefined=structuredClone(inputs);ownUndefined.species.rows[0][8]=true;ownUndefined.species.rows[0][7]={u:1};assert.deepEqual(validate(ownUndefined),result);const mutations=[d=>d.abilities.runtime_slots[0]=1,d=>d.abilities.runtime_slots[1]=1,d=>{d.species.rows[0][8]=true;d.species.rows[0][7]=null;},d=>{d.species.rows[0][8]=true;d.species.rows[0][7]='33';},d=>d.species.form_data[0][5]=512,d=>d.species.form_data.push(d.species.form_data[0]),d=>d.species.shapes.push(d.species.shapes[0]),d=>d.species.roots.pop(),d=>d.species.rows.pop(),d=>d.moves.rows.pop(),d=>d.abilities.rows.pop(),d=>d.species.wild_kind=1,d=>d.species.context.wave=1,d=>d.species.level_sets[0][0].push([11,33]),d=>d.species.rows[0][0]=0,d=>d.gender.rows.pop(),d=>d.gender.rows[0][0]=0,d=>d.gender.rows[0][1]=-1,d=>d.gender.source='other',d=>d.formFlags.rows.pop(),d=>d.formFlags.rows[0][0]=0,d=>d.formFlags.rows[0][1]=2**d.species.rows[0][6].length,d=>d.abilitySlots.rows.pop(),d=>d.abilitySlots.rows[0][0]=0,d=>d.abilitySlots.rows[0][1].pop(),d=>d.abilitySlots.rows[0][1][0][0]=0,d=>d.abilitySlots.source='other',d=>d.formTypes.rows.pop(),d=>d.formTypes.rows[0][1][0][0]=-1,d=>d.formTypes.source='other',d=>d.formStats.rows.pop(),d=>d.formStats.rows[0][1][0][0]=-1,d=>d.formStats.source='other',d=>d.levelTwoForms.rows.pop(),d=>d.levelTwoForms.rows[0][1][0].push([2,99999]),d=>d.levelTwoForms.source='other',d=>d.levelTwoMeta.rows.pop(),d=>d.levelTwoMeta.rows[0][1]=-1,d=>d.levelTwoMeta.source='other'];for(const mutate of mutations){const d=structuredClone(inputs);mutate(d);assert.throws(()=>validate(d));}
for(const mutate of [d=>d.levelTwoMovegen.rows.pop(),d=>d.levelTwoMovegen.rows[0][2]=256,d=>d.levelTwoMovegen.source='other',d=>d.levelTwoAbilities.rows.pop(),d=>d.levelTwoAbilities.rows[0][1][0][0][0]=0,d=>d.levelTwoAbilities.movegen_modifiers.pop(),d=>d.levelTwoAbilities.source='other']){const d=structuredClone(inputs);mutate(d);assert.throws(()=>validate(d));}
const output=Buffer.from(JSON.stringify({schema:1,status:'passed',scope:'complete static registry closure for all effective Town roots; no executable compiler or natural encounter qualification',facts,form_count_receipt:{bytes:countRaw.length,sha256:hash(countRaw)},identical_fresh_processes:2,negative_checks:mutations.length+packedMutations.length+formsMutations.length+7,...result})+'\n');assert(output.length<=8192);writeFileSync(process.argv[3],output,{flag:'wx'});
