import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,lstatSync} from 'node:fs';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
assert.equal(process.argv.length,4);const dir=process.argv[2],hash=b=>createHash('sha256').update(b).digest('hex');
const shape=(v,keys)=>assert.deepEqual(Object.keys(v).sort(),[...keys].sort());const int=(n,a,b)=>assert(Number.isSafeInteger(n)&&n>=a&&n<=b);
const inputs={};const facts={};for(const [name,cap] of [['species',32768],['moves',32768],['abilities',16384]]){const raws=['one','two'].map(n=>{const p=join(dir,`${name}-${n}.json`),s=lstatSync(p);assert(s.isFile()&&!s.isSymbolicLink()&&s.size<=cap);return readFileSync(p);});assert(raws[0].equals(raws[1]));inputs[name]=JSON.parse(raws[0]);facts[name]={bytes:raws[0].length,sha256:hash(raws[0])};}
function decode(value,part,depth=0){
 const {functions,shapes}=part;
 assert(depth<=12);if(value===null||typeof value==='boolean'||typeof value==='string'){if(typeof value==='string')assert(value.length<=1024);return value;}
 if(typeof value==='number'){assert(Number.isFinite(value));return value;}
 if(Array.isArray(value)){assert(value.length<=512);return value.map(v=>decode(v,part,depth+1));}
 assert(typeof value==='object');const keys=Object.keys(value);
 if(keys.length===1&&keys[0]==='m'){assert(Array.isArray(value.m)&&value.m.length<=512);return new Map(value.m.map(r=>{assert(Array.isArray(r)&&r.length===2);return r.map(x=>decode(x,part,depth+1));}));}
 if(keys.length===1&&keys[0]==='s'){assert(Array.isArray(value.s)&&value.s.length<=512);return new Set(value.s.map(v=>decode(v,part,depth+1)));}
 if(keys.length===1&&keys[0]==='u'){assert.equal(value.u,1);return undefined;}
 if(keys.length===1&&keys[0]==='n'){assert(['NaN','Infinity','-Infinity'].includes(value.n));return Number(value.n);}
 if(keys.length===1&&keys[0]==='f'){int(value.f,0,functions.length-1);return {sourceFunction:value.f};}
 shape(value,['o']);assert(Array.isArray(value.o)&&value.o.length===2);const [index,values]=value.o;int(index,0,shapes.length-1);const fieldKeys=shapes[index][1];assert(Array.isArray(values)&&values.length===fieldKeys.length);const out=Object.create(null);for(let i=0;i<fieldKeys.length;i++){if(shapes[index][0]==='NullifyFirstNHitsAbAttr'&&fieldKeys[i]==='usage'){assert.deepEqual(part.runtime_slots,[0,0]);assert.deepEqual(values[i],{w:0});out[fieldKeys[i]]={freshConstructorRuntimeSlot:'NullifyFirstNHitsAbAttr.usage'};}else out[fieldKeys[i]]=decode(values[i],part,depth+1);}return out;

}
const countPath=join(dir,'form-counts.json'),countStat=lstatSync(countPath);assert(countStat.isFile()&&!countStat.isSymbolicLink()&&countStat.size<=4096);const countRaw=readFileSync(countPath),countReceipt=JSON.parse(countRaw);shape(countReceipt,['source','scope','roots','visited','max_forms','counts']);assert.equal(countReceipt.source,'399d5d368f0b5642ebf8f45bd8a5e73350fa4de7');assert.equal(countReceipt.scope,'complete visited Town evolution graph source form counts before payload extraction');assert.equal(countReceipt.roots,54);assert.equal(countReceipt.max_forms,20);
function validate(d){
 for(const part of Object.values(d)){assert.equal(part.schema,2);assert.equal(part.source,'399d5d368f0b5642ebf8f45bd8a5e73350fa4de7');assert(Array.isArray(part.functions)&&part.functions.length<=512);assert(Array.isArray(part.shapes)&&part.shapes.length<=512);assert.equal(new Set(part.shapes.map(s=>JSON.stringify(s))).size,part.shapes.length);for(const row of part.shapes){assert(Array.isArray(row)&&row.length===2);assert(row[0]===null||(typeof row[0]==='string'&&row[0].length<=128));assert(Array.isArray(row[1])&&row[1].length<=128&&row[1].every(k=>typeof k==='string'));assert.equal(new Set(row[1]).size,row[1].length);}for(const f of part.functions){assert(Array.isArray(f)&&f.length===2&&/^[a-f0-9]{64}$/.test(f[0]));int(f[1],1,65536);}}
 const s=d.species;shape(s,['schema','source','roots','tiers','level_cap','wild_kind','context','rows','functions','shapes','form_data','level_sets']);assert.equal(s.level_cap,10);assert.equal(s.wild_kind,2);
 shape(s.context,['wave','biome','difficulty','time','luck','forced','regional']);assert.equal(s.context.wave,2);assert.equal(s.context.biome,0);assert(['ace','youngster','elite','hell','mystery'].includes(s.context.difficulty));int(s.context.time,0,12);assert(Number.isFinite(s.context.luck)&&s.context.luck>=0&&s.context.luck<=100);if(s.context.forced!==null)int(s.context.forced,0,12);if(s.context.regional!==null)assert.equal(typeof s.context.regional,'boolean');
 assert(Array.isArray(s.tiers)&&s.tiers.length>0&&s.tiers.length<=12);let last=-1;for(const r of s.tiers){assert(Array.isArray(r)&&r.length===2);int(r[0],0,12);assert(r[0]>last);last=r[0];assert(Array.isArray(r[1])&&r[1].length<=128);for(const id of r[1])int(id,1,100000);}
 assert.deepEqual(s.roots,[...new Set(s.tiers.flatMap(r=>r[1]))]);assert.equal(s.roots.length,54);assert(Array.isArray(s.rows)&&s.rows.length>=54&&s.rows.length<=256);
 assert(Array.isArray(s.form_data)&&s.form_data.length>0&&s.form_data.length<=512);assert(Array.isArray(s.level_sets)&&s.level_sets.length>0&&s.level_sets.length<=512);
 assert.equal(new Set(s.form_data.map(r=>JSON.stringify(r))).size,s.form_data.length);assert.equal(new Set(s.level_sets.map(r=>JSON.stringify(r))).size,s.level_sets.length);
 const usedForms=new Set(),usedLevels=new Set();
 const nodes=new Map(),moveIds=[],abilityIds=[];const add=(list,id)=>{int(id,0,100000);if(!list.includes(id))list.push(id);};
 for(const n of s.rows){assert(Array.isArray(n)&&n.length===10);const [id,evoOwn,e,preOwn,p,pl,forms,sig,sigOwn,incoming]=n;int(id,1,100000);assert(!nodes.has(id));for(const flag of [evoOwn,preOwn,sigOwn])assert.equal(typeof flag,'boolean');const evos=decode(e,s),pre=decode(p,s),preLevels=decode(pl,s),signature=decode(sig,s);assert(Array.isArray(evos)&&evos.length<=128);if(!evoOwn)assert.equal(evos.length,0);if(preOwn)int(pre,1,100000);else assert.equal(pre,undefined);if(!sigOwn)assert.equal(signature,undefined);else if(signature!==undefined){assert(typeof signature==='number'||Array.isArray(signature));const ids=Array.isArray(signature)?signature:[signature];assert(ids.length<=32);for(const x of ids)int(x,1,100000);}
 assert(Array.isArray(preLevels)&&preLevels.length<=128);for(const row of preLevels){assert(Array.isArray(row)&&row.length>=2&&row.length<=3);int(row[0],1,100000);}
 assert(Array.isArray(forms)&&forms.length>0&&forms.length<=20);for(const [i,binding] of forms.entries()){
  assert(Array.isArray(binding)&&binding.length===3);assert.equal(binding[0],i);assert(binding[1]===null||typeof binding[1]==='string');int(binding[2],0,s.form_data.length-1);usedForms.add(binding[2]);const f=s.form_data[binding[2]];assert(Array.isArray(f)&&f.length===6);
  int(f[0],0,32);if(f[1]!==null)int(f[1],0,32);assert(Array.isArray(f[2])&&f[2].length===6);f[2].forEach(x=>int(x,1,10000));assert(Array.isArray(f[3])&&f[3].length>=2&&f[3].length<=3);assert(Array.isArray(f[4])&&f[4].length===3);[...f[3],...f[4]].forEach(x=>add(abilityIds,x));int(f[5],0,s.level_sets.length-1);usedLevels.add(f[5]);const levels=s.level_sets[f[5]];assert(Array.isArray(levels)&&levels.length===3);assert(Array.isArray(levels[0])&&levels[0].length<=512);for(const row of levels[0]){assert(Array.isArray(row)&&row.length===2);int(row[0],-2,10);add(moveIds,row[1]);}int(levels[1],levels[0].length,512);assert(/^[a-f0-9]{64}$/.test(levels[2]));}
 assert(Array.isArray(incoming)&&incoming.length<=128);for(const row of incoming){assert(Array.isArray(row)&&row.length===2);int(row[0],1,100000);int(row[1],0,127);}
 nodes.set(id,{evos,preOwn,pre,preLevels,incoming});}
 assert.equal(usedForms.size,s.form_data.length);assert.equal(usedLevels.size,s.level_sets.length);
 for(const [id,node] of nodes){const incoming=[...nodes].sort(([a],[b])=>a-b).flatMap(([parent,n])=>n.evos.flatMap((e,index)=>e.speciesId===id?[[parent,index]]:[]));assert.deepEqual(node.incoming,incoming);}
 const seen=new Set(),queue=s.roots.map(id=>[id,0]);for(let i=0;i<queue.length;i++){const [id,depth]=queue[i];if(seen.has(id))continue;int(depth,0,32);assert(nodes.has(id));seen.add(id);const n=nodes.get(id);for(const e of n.evos){int(e.speciesId,1,100000);queue.push([e.speciesId,depth+1]);}for(const row of n.preLevels)queue.push([row[0],depth+1]);if(n.preOwn)queue.push([n.pre,depth+1]);for(const [parent,index] of n.incoming){assert(nodes.has(parent)&&nodes.get(parent).evos[index]?.speciesId===id);queue.push([parent,depth+1]);}}assert.deepEqual([...nodes.keys()],[...seen]);
 const m=d.moves;shape(m,['schema','source','rows','functions','shapes','tuning']);assert.deepEqual(m.rows.map(r=>r[0]),moveIds);assert(m.rows.length<=512);assert(m.tuning.length===7);for(const n of m.tuning)assert(Number.isFinite(n)&&n>0&&n<=1000);
 for(const row of m.rows){assert(Array.isArray(row));assert.equal(typeof row[1],'boolean');if(!row[1]){assert.equal(row.length,2);continue;}assert.equal(row.length,13);int(row[2],0,2);int(row[3],0,32);assert(Number.isFinite(row[4]));assert(Number.isFinite(row[5]));for(const i of [6,7,11,12])assert.equal(typeof row[i],'boolean');assert(typeof row[8]==='string');assert(Array.isArray(decode(row[9],m)));decode(row[10],m);}
 const a=d.abilities;shape(a,['schema','source','rows','functions','shapes','runtime_slots']);assert.deepEqual(a.runtime_slots,[0,0]);assert.deepEqual(a.rows.map(r=>r[0]),abilityIds);assert(a.rows.length<=512);for(const row of a.rows){assert(row.length===2);assert(Array.isArray(decode(row[1],a)));}
 assert.deepEqual(countReceipt.counts,s.rows.map(n=>[n[0],n[6].length]));assert.equal(countReceipt.visited,s.rows.length);assert.equal(Math.max(...countReceipt.counts.map(r=>r[1])),countReceipt.max_forms);
 const eligibility=[];for(const id of s.roots)for(let level=1;level<=10;level++){const n=nodes.get(id);let forced=null;if(n.preOwn)for(let i=n.preLevels.length-1;i>=0;i--){const [pre,req,thresholds]=n.preLevels[i],threshold=thresholds?.[s.wild_kind]??req;if(level<(req===1?threshold:Math.min(req,threshold))){forced=pre;break;}}const eligible=forced===null?n.evos.flatMap(e=>{const threshold=Math.max(e.level,e.evoLevelThreshold?.[s.wild_kind]??0);return level<e.level||level<threshold||!(threshold>0)?[]:[[threshold,e.speciesId]];}):[];eligibility.push([id,level,forced,eligible]);}
 return {roots:s.roots.length,species:s.rows.length,moves:m.rows.length,abilities:a.rows.length,eligibility_sha256:hash(JSON.stringify(eligibility)),level2_forced:eligibility.filter(r=>r[1]===2&&r[2]!==null).map(r=>[r[0],r[2]]),level2_upward_roots:eligibility.filter(r=>r[1]===2&&r[3].length>0).map(r=>r[0])};
}
const result=validate(inputs);const ownUndefined=structuredClone(inputs);ownUndefined.species.rows[0][8]=true;ownUndefined.species.rows[0][7]={u:1};assert.deepEqual(validate(ownUndefined),result);const mutations=[d=>d.abilities.runtime_slots[0]=1,d=>d.abilities.runtime_slots[1]=1,d=>{d.species.rows[0][8]=true;d.species.rows[0][7]=null;},d=>{d.species.rows[0][8]=true;d.species.rows[0][7]='33';},d=>d.species.form_data[0][5]=512,d=>d.species.form_data.push(d.species.form_data[0]),d=>d.species.shapes.push(d.species.shapes[0]),d=>d.species.roots.pop(),d=>d.species.rows.pop(),d=>d.moves.rows.pop(),d=>d.abilities.rows.pop(),d=>d.species.wild_kind=1,d=>d.species.context.wave=1,d=>d.species.level_sets[0][0].push([11,33]),d=>d.species.rows[0][0]=0];for(const mutate of mutations){const d=structuredClone(inputs);mutate(d);assert.throws(()=>validate(d));}
const output=Buffer.from(JSON.stringify({schema:1,status:'passed',scope:'complete static registry closure for all effective Town roots; no executable compiler or natural encounter qualification',facts,form_count_receipt:{bytes:countRaw.length,sha256:hash(countRaw)},identical_fresh_processes:2,negative_checks:mutations.length,...result})+'\n');assert(output.length<=8192);writeFileSync(process.argv[3],output,{flag:'wx'});
