import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,lstatSync} from 'node:fs';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
assert.equal(process.argv.length,4);const dir=process.argv[2],hash=b=>createHash('sha256').update(b).digest('hex');
const shape=(v,keys)=>assert.deepEqual(Object.keys(v).sort(),[...keys].sort());const int=(n,a,b)=>assert(Number.isSafeInteger(n)&&n>=a&&n<=b);
const inputs={};const facts={};for(const [name,cap] of [['species',32768],['moves',32768],['abilities',16384]]){const raws=['one','two'].map(n=>{const p=join(dir,`${name}-${n}.json`),s=lstatSync(p);assert(s.isFile()&&!s.isSymbolicLink()&&s.size<=cap);return readFileSync(p);});assert(raws[0].equals(raws[1]));inputs[name]=JSON.parse(raws[0]);facts[name]={bytes:raws[0].length,sha256:hash(raws[0])};}
function decode(value,functions,depth=0){
 assert(depth<=12);if(value===null||typeof value==='boolean'||typeof value==='string'){if(typeof value==='string')assert(value.length<=1024);return value;}
 if(typeof value==='number'){assert(Number.isFinite(value));return value;}
 if(Array.isArray(value)){assert(value.length<=512);return value.map(v=>decode(v,functions,depth+1));}
 assert(typeof value==='object');const keys=Object.keys(value);
 if(keys.length===1&&keys[0]==='m'){assert(Array.isArray(value.m)&&value.m.length<=512);return new Map(value.m.map(r=>{assert(Array.isArray(r)&&r.length===2);return r.map(x=>decode(x,functions,depth+1));}));}
 if(keys.length===1&&keys[0]==='s'){assert(Array.isArray(value.s)&&value.s.length<=512);return new Set(value.s.map(v=>decode(v,functions,depth+1)));}
 if(keys.length===1&&keys[0]==='u'){assert.equal(value.u,1);return undefined;}
 if(keys.length===1&&keys[0]==='n'){assert(['NaN','Infinity','-Infinity'].includes(value.n));return Number(value.n);}
 if(keys.length===1&&keys[0]==='f'){int(value.f,0,functions.length-1);return {sourceFunction:value.f};}
 shape(value,['c','p']);assert(value.c===null||(typeof value.c==='string'&&value.c.length<=128));assert(Array.isArray(value.p)&&value.p.length<=128);const out=Object.create(null);for(const row of value.p){assert(Array.isArray(row)&&row.length===2&&typeof row[0]==='string');assert(!Object.hasOwn(out,row[0]));out[row[0]]=decode(row[1],functions,depth+1);}return out;
}
function validate(d){
 for(const part of Object.values(d)){assert.equal(part.schema,1);assert.equal(part.source,'399d5d368f0b5642ebf8f45bd8a5e73350fa4de7');assert(Array.isArray(part.functions)&&part.functions.length<=512);for(const f of part.functions){assert(Array.isArray(f)&&f.length===2&&/^[a-f0-9]{64}$/.test(f[0]));int(f[1],1,65536);}}
 const s=d.species;shape(s,['schema','source','roots','tiers','level_cap','wild_kind','context','rows','functions']);assert.equal(s.level_cap,10);assert.equal(s.wild_kind,2);
 shape(s.context,['wave','biome','difficulty','time','luck','forced','regional']);assert.equal(s.context.wave,2);assert.equal(s.context.biome,0);assert(['ace','youngster','elite','hell','mystery'].includes(s.context.difficulty));int(s.context.time,0,12);assert(Number.isFinite(s.context.luck)&&s.context.luck>=0&&s.context.luck<=100);if(s.context.forced!==null)int(s.context.forced,0,12);if(s.context.regional!==null)assert.equal(typeof s.context.regional,'boolean');
 assert(Array.isArray(s.tiers)&&s.tiers.length>0&&s.tiers.length<=12);let last=-1;for(const r of s.tiers){assert(Array.isArray(r)&&r.length===2);int(r[0],0,12);assert(r[0]>last);last=r[0];assert(Array.isArray(r[1])&&r[1].length<=128);for(const id of r[1])int(id,1,100000);}
 assert.deepEqual(s.roots,[...new Set(s.tiers.flatMap(r=>r[1]))]);assert.equal(s.roots.length,54);assert(Array.isArray(s.rows)&&s.rows.length>=54&&s.rows.length<=256);
 const nodes=new Map(),moveIds=[],abilityIds=[];const add=(list,id)=>{int(id,0,100000);if(!list.includes(id))list.push(id);};
 for(const n of s.rows){assert(Array.isArray(n)&&n.length===10);const [id,evoOwn,e,preOwn,p,pl,forms,sig,sigOwn,incoming]=n;int(id,1,100000);assert(!nodes.has(id));for(const flag of [evoOwn,preOwn,sigOwn])assert.equal(typeof flag,'boolean');const evos=decode(e,s.functions),pre=decode(p,s.functions),preLevels=decode(pl,s.functions),signature=decode(sig,s.functions);assert(Array.isArray(evos)&&evos.length<=128);if(!evoOwn)assert.equal(evos.length,0);if(preOwn)int(pre,1,100000);else assert.equal(pre,undefined);if(!sigOwn)assert.equal(signature,undefined);else{const ids=Array.isArray(signature)?signature:[signature];assert(ids.length<=32);for(const x of ids)int(x,1,100000);}
 assert(Array.isArray(preLevels)&&preLevels.length<=128);for(const row of preLevels){assert(Array.isArray(row)&&row.length>=2&&row.length<=3);int(row[0],1,100000);}
 assert(Array.isArray(forms)&&forms.length>0&&forms.length<=16);for(const [i,f] of forms.entries()){assert(Array.isArray(f)&&f.length===10);assert.equal(f[0],i);assert(f[1]===null||typeof f[1]==='string');int(f[2],0,32);if(f[3]!==null)int(f[3],0,32);assert(Array.isArray(f[4])&&f[4].length===6);f[4].forEach(x=>int(x,1,10000));assert(Array.isArray(f[5])&&f[5].length>=2&&f[5].length<=3);assert(Array.isArray(f[6])&&f[6].length===3);[...f[5],...f[6]].forEach(x=>add(abilityIds,x));assert(Array.isArray(f[7])&&f[7].length<=512);for(const row of f[7]){assert(Array.isArray(row)&&row.length===2);int(row[0],-2,10);add(moveIds,row[1]);}int(f[8],f[7].length,512);assert(/^[a-f0-9]{64}$/.test(f[9]));}
 assert(Array.isArray(incoming)&&incoming.length<=128);for(const row of incoming){assert(Array.isArray(row)&&row.length===2);int(row[0],1,100000);int(row[1],0,127);}
 nodes.set(id,{evos,preOwn,pre,preLevels,incoming});}
 for(const [id,node] of nodes){const incoming=[...nodes].sort(([a],[b])=>a-b).flatMap(([parent,n])=>n.evos.flatMap((e,index)=>e.speciesId===id?[[parent,index]]:[]));assert.deepEqual(node.incoming,incoming);}
 const seen=new Set(),queue=s.roots.map(id=>[id,0]);for(let i=0;i<queue.length;i++){const [id,depth]=queue[i];if(seen.has(id))continue;int(depth,0,32);assert(nodes.has(id));seen.add(id);const n=nodes.get(id);for(const e of n.evos){int(e.speciesId,1,100000);queue.push([e.speciesId,depth+1]);}for(const row of n.preLevels)queue.push([row[0],depth+1]);if(n.preOwn)queue.push([n.pre,depth+1]);for(const [parent,index] of n.incoming){assert(nodes.has(parent)&&nodes.get(parent).evos[index]?.speciesId===id);queue.push([parent,depth+1]);}}assert.deepEqual([...nodes.keys()],[...seen]);
 const m=d.moves;shape(m,['schema','source','rows','functions','tuning']);assert.deepEqual(m.rows.map(r=>r[0]),moveIds);assert(m.rows.length<=512);assert(m.tuning.length===7);for(const n of m.tuning)assert(Number.isFinite(n)&&n>0&&n<=1000);
 for(const row of m.rows){assert(Array.isArray(row));assert.equal(typeof row[1],'boolean');if(!row[1]){assert.equal(row.length,2);continue;}assert.equal(row.length,13);int(row[2],0,2);int(row[3],0,32);assert(Number.isFinite(row[4]));assert(Number.isFinite(row[5]));for(const i of [6,7,11,12])assert.equal(typeof row[i],'boolean');assert(typeof row[8]==='string');assert(Array.isArray(decode(row[9],m.functions)));decode(row[10],m.functions);}
 const a=d.abilities;shape(a,['schema','source','rows','functions']);assert.deepEqual(a.rows.map(r=>r[0]),abilityIds);assert(a.rows.length<=512);for(const row of a.rows){assert(row.length===2);assert(Array.isArray(decode(row[1],a.functions)));}
 const eligibility=[];for(const id of s.roots)for(let level=1;level<=10;level++){const n=nodes.get(id);let forced=null;if(n.preOwn)for(let i=n.preLevels.length-1;i>=0;i--){const [pre,req,thresholds]=n.preLevels[i],threshold=thresholds?.[s.wild_kind]??req;if(level<(req===1?threshold:Math.min(req,threshold))){forced=pre;break;}}const eligible=forced===null?n.evos.flatMap(e=>{const threshold=Math.max(e.level,e.evoLevelThreshold?.[s.wild_kind]??0);return level<e.level||level<threshold||!(threshold>0)?[]:[[threshold,e.speciesId]];}):[];eligibility.push([id,level,forced,eligible]);}
 return {roots:s.roots.length,species:s.rows.length,moves:m.rows.length,abilities:a.rows.length,eligibility_sha256:hash(JSON.stringify(eligibility)),level2_forced:eligibility.filter(r=>r[1]===2&&r[2]!==null).map(r=>[r[0],r[2]]),level2_upward_roots:eligibility.filter(r=>r[1]===2&&r[3].length>0).map(r=>r[0])};
}
const result=validate(inputs);const mutations=[d=>d.species.roots.pop(),d=>d.species.rows.pop(),d=>d.moves.rows.pop(),d=>d.abilities.rows.pop(),d=>d.species.wild_kind=1,d=>d.species.context.wave=1,d=>d.species.rows[0][6][0][7].push([11,33]),d=>d.species.rows[0][0]=0];for(const mutate of mutations){const d=structuredClone(inputs);mutate(d);assert.throws(()=>validate(d));}
const output=Buffer.from(JSON.stringify({schema:1,status:'passed',scope:'complete static registry closure for all effective Town roots; no executable compiler or natural encounter qualification',facts,identical_fresh_processes:2,negative_checks:mutations.length,...result})+'\n');assert(output.length<=8192);writeFileSync(process.argv[3],output,{flag:'wx'});
