/*
 * SPDX-FileCopyrightText: 2024-2026 Pagefault Games
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// =============================================================================
// Move-audit worktable GENERATOR (scenario test, gated ER_SCENARIO=1).
//
// Emits docs/plans/er-move-audit-worktable.md — the per-move analog of the
// ability worktable. For every ER move it joins:
//   - ABBR / FULL — the in-game descriptions (er-moves.ts description /
//     longDescription) = the authoritative spec, mirroring the ROM detail screens.
//   - ROM — the ER move's declared spec decoded to the detail-screen fields
//     (power/acc/pp/priority/effect#/chance/target/split + decoded ER flags:
//     contact, boost type, high-crit, etc.).
//   - CODE — the LIVE runtime wiring after full ER init: the Move's resolved
//     type, category, power, accuracy, MoveFlags, and attr class names.
//
// The audit then walks this file chunk-by-chunk (descriptions are authoritative)
// and reconciles "what the ROM screen says" vs "what the engine does".
// =============================================================================

import { allMoves } from "#data/data-lists";
import { ER_FLAG_NAMES_LIST } from "#data/elite-redux/er-flag-mapping";
import { ER_ID_MAP } from "#data/elite-redux/er-id-map";
import { ER_MOVES } from "#data/elite-redux/er-moves";
import { MoveCategory } from "#enums/move-category";
import { MoveFlags } from "#enums/move-flags";
import { PokemonType } from "#enums/pokemon-type";
import { writeFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const RUN = process.env.ER_SCENARIO === "1";

// Numeric MoveFlags entries (skip NONE / non-numeric reverse-map keys).
const MOVE_FLAG_ENTRIES = Object.entries(MoveFlags).filter(([, v]) => typeof v === "number" && (v as number) > 0) as [
  string,
  number,
][];

function decodeErFlags(flags: number[] | undefined): string {
  if (!flags || flags.length === 0) {
    return "-";
  }
  return flags.map(i => ER_FLAG_NAMES_LIST[i] ?? `flag#${i}`).join(", ");
}

function decodeLiveFlags(move: { hasFlag(f: number): boolean }): string {
  const names = MOVE_FLAG_ENTRIES.filter(([, v]) => move.hasFlag(v)).map(([k]) => k);
  return names.length > 0 ? names.join(", ") : "-";
}

describe.skipIf(!RUN)("ER move-audit worktable generator", () => {
  it("writes docs/plans/er-move-audit-worktable.md", () => {
    const lines: string[] = [];
    lines.push("# ER Move Audit — Worktable (auto-generated)");
    lines.push("");
    lines.push("Per-move spec (ABBR/FULL = in-game descriptions, the authoritative source) + ROM-declared fields");
    lines.push(
      "(decoded to the in-game detail-screen layout) + CODE (live runtime type/category/power/acc/flags/attrs",
    );
    lines.push("after full ER init). Audit each move's wiring against its description, chunk-by-chunk.");
    lines.push("");

    const moves = [...(ER_MOVES as any[])].filter(m => m.id > 0 && m.name && m.name !== "-");
    moves.sort((a, b) => a.id - b.id);

    let customCount = 0;
    let noLive = 0;

    for (const m of moves) {
      const pk = (ER_ID_MAP as any).moves?.[m.id];
      const isCustom = typeof pk === "number" && pk >= 5000;
      if (isCustom) {
        customCount++;
      }
      const live = typeof pk === "number" ? allMoves[pk] : undefined;

      lines.push(`### ${m.id} ${m.name}  [${m.archetype}] pk=${pk ?? "?"}${isCustom ? " (custom)" : ""}`);
      lines.push(`  ABBR: ${m.description ?? ""}`);
      lines.push(`  FULL: ${m.longDescription ?? ""}`);
      lines.push(
        `  ROM: pow=${m.power} acc=${m.accuracy} pp=${m.pp} prio=${m.priority} split=${m.split} `
          + `target=${m.target} effect=${m.effect} chance=${m.effectChance} usesHpType=${m.usesHpType} `
          + `| flags=[${decodeErFlags(m.flags)}]`,
      );
      if (live) {
        lines.push(
          `  CODE: type=${PokemonType[(live as any).type]} cat=${MoveCategory[(live as any).category]} `
            + `pow=${(live as any).power} acc=${(live as any).accuracy} `
            + `flags=[${decodeLiveFlags(live as any)}] attrs=[${(live as any).attrs.map((a: any) => a.constructor.name).join(", ")}]`,
        );
      } else {
        lines.push("  CODE: (no live move)");
        noLive++;
      }
      lines.push("");
    }

    lines.unshift(
      `Total moves: ${moves.length} (custom: ${customCount}, no-live: ${noLive}). Generated by er-move-worktable-gen.test.ts.`,
    );

    writeFileSync("docs/plans/er-move-audit-worktable.md", lines.join("\n"), "utf8");
    console.log(`### WORKTABLE written: ${moves.length} moves (${customCount} custom, ${noLive} no-live)`);
    expect(moves.length).toBeGreaterThan(700);
  });
});
