//! Source-generated base pool identities/rules from cached399d
//! src/modifier/init-modifier-pools.ts. No observed reward list is embedded.
use super::current_reward_tuning::{Row, Weight};
pub(crate) fn base() -> [Vec<Row<()>>; 5] {
    [
        vec![
            Row {
                ordinal: 0,
                id: "POKEBALL",
                weight: Weight::SourcePredicate("POKEBALL"),
                payload: (),
            },
            Row {
                ordinal: 1,
                id: "RARE_CANDY",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 2,
                id: "POTION",
                weight: Weight::SourcePredicate("POTION"),
                payload: (),
            },
            Row {
                ordinal: 3,
                id: "SUPER_POTION",
                weight: Weight::SourcePredicate("SUPER_POTION"),
                payload: (),
            },
            Row {
                ordinal: 4,
                id: "ETHER",
                weight: Weight::SourcePredicate("ETHER"),
                payload: (),
            },
            Row {
                ordinal: 5,
                id: "MAX_ETHER",
                weight: Weight::SourcePredicate("MAX_ETHER"),
                payload: (),
            },
            Row {
                ordinal: 6,
                id: "LURE",
                weight: Weight::SourcePredicate("LURE"),
                payload: (),
            },
            Row {
                ordinal: 7,
                id: "TEMP_STAT_STAGE_BOOSTER",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 8,
                id: "BERRY",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 9,
                id: "TM_CASE",
                weight: Weight::Fixed(2),
                payload: (),
            },
        ],
        vec![
            Row {
                ordinal: 10,
                id: "GREAT_BALL",
                weight: Weight::SourcePredicate("GREAT_BALL"),
                payload: (),
            },
            Row {
                ordinal: 11,
                id: "PP_UP",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 12,
                id: "FULL_HEAL",
                weight: Weight::SourcePredicate("FULL_HEAL"),
                payload: (),
            },
            Row {
                ordinal: 13,
                id: "REVIVE",
                weight: Weight::SourcePredicate("REVIVE"),
                payload: (),
            },
            Row {
                ordinal: 14,
                id: "MAX_REVIVE",
                weight: Weight::SourcePredicate("MAX_REVIVE"),
                payload: (),
            },
            Row {
                ordinal: 15,
                id: "SACRED_ASH",
                weight: Weight::SourcePredicate("SACRED_ASH"),
                payload: (),
            },
            Row {
                ordinal: 16,
                id: "HYPER_POTION",
                weight: Weight::SourcePredicate("HYPER_POTION"),
                payload: (),
            },
            Row {
                ordinal: 17,
                id: "MAX_POTION",
                weight: Weight::SourcePredicate("MAX_POTION"),
                payload: (),
            },
            Row {
                ordinal: 18,
                id: "FULL_RESTORE",
                weight: Weight::SourcePredicate("FULL_RESTORE"),
                payload: (),
            },
            Row {
                ordinal: 19,
                id: "ELIXIR",
                weight: Weight::SourcePredicate("ELIXIR"),
                payload: (),
            },
            Row {
                ordinal: 20,
                id: "MAX_ELIXIR",
                weight: Weight::SourcePredicate("MAX_ELIXIR"),
                payload: (),
            },
            Row {
                ordinal: 21,
                id: "DIRE_HIT",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 22,
                id: "SUPER_LURE",
                weight: Weight::SourcePredicate("SUPER_LURE"),
                payload: (),
            },
            Row {
                ordinal: 23,
                id: "NUGGET",
                weight: Weight::SourcePredicate("NUGGET"),
                payload: (),
            },
            Row {
                ordinal: 24,
                id: "SPECIES_STAT_BOOSTER",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 25,
                id: "EVOLUTION_ITEM",
                weight: Weight::SourcePredicate("EVOLUTION_ITEM"),
                payload: (),
            },
            Row {
                ordinal: 26,
                id: "ER_UPGRADED_MAP",
                weight: Weight::SourcePredicate("ER_UPGRADED_MAP"),
                payload: (),
            },
            Row {
                ordinal: 27,
                id: "SOOTHE_BELL",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 28,
                id: "MEMORY_MUSHROOM",
                weight: Weight::SourcePredicate("MEMORY_MUSHROOM"),
                payload: (),
            },
            Row {
                ordinal: 29,
                id: "ER_ABILITY_CAPSULE",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 30,
                id: "ER_EJECT_BUTTON",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 31,
                id: "ER_EJECT_PACK",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 32,
                id: "ER_SHED_SHELL",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 33,
                id: "ER_ADRENALINE_ORB",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 34,
                id: "ER_ROOM_SERVICE",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 35,
                id: "ER_MENTAL_HERB",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 36,
                id: "ER_BLUNDER_POLICY",
                weight: Weight::SourcePredicate("ER_BLUNDER_POLICY"),
                payload: (),
            },
            Row {
                ordinal: 37,
                id: "ER_STICKY_BARB",
                weight: Weight::SourcePredicate("ER_STICKY_BARB"),
                payload: (),
            },
            Row {
                ordinal: 38,
                id: "BASE_STAT_BOOSTER",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 39,
                id: "TERA_SHARD",
                weight: Weight::SourcePredicate("TERA_SHARD"),
                payload: (),
            },
            Row {
                ordinal: 40,
                id: "DNA_SPLICERS",
                weight: Weight::SourcePredicate("DNA_SPLICERS"),
                payload: (),
            },
            Row {
                ordinal: 41,
                id: "VOUCHER",
                weight: Weight::SourcePredicate("VOUCHER"),
                payload: (),
            },
        ],
        vec![
            Row {
                ordinal: 42,
                id: "ULTRA_BALL",
                weight: Weight::SourcePredicate("ULTRA_BALL"),
                payload: (),
            },
            Row {
                ordinal: 43,
                id: "MAX_LURE",
                weight: Weight::SourcePredicate("MAX_LURE"),
                payload: (),
            },
            Row {
                ordinal: 44,
                id: "BIG_NUGGET",
                weight: Weight::SourcePredicate("BIG_NUGGET"),
                payload: (),
            },
            Row {
                ordinal: 45,
                id: "PP_MAX",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 46,
                id: "MINT",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 47,
                id: "RARE_EVOLUTION_ITEM",
                weight: Weight::SourcePredicate("RARE_EVOLUTION_ITEM"),
                payload: (),
            },
            Row {
                ordinal: 48,
                id: "FORM_CHANGE_ITEM",
                weight: Weight::SourcePredicate("FORM_CHANGE_ITEM"),
                payload: (),
            },
            Row {
                ordinal: 49,
                id: "AMULET_COIN",
                weight: Weight::SourcePredicate("AMULET_COIN"),
                payload: (),
            },
            Row {
                ordinal: 50,
                id: "EVIOLITE",
                weight: Weight::SourcePredicate("EVIOLITE"),
                payload: (),
            },
            Row {
                ordinal: 51,
                id: "RARE_SPECIES_STAT_BOOSTER",
                weight: Weight::Fixed(12),
                payload: (),
            },
            Row {
                ordinal: 52,
                id: "LEEK",
                weight: Weight::SourcePredicate("LEEK"),
                payload: (),
            },
            Row {
                ordinal: 53,
                id: "TOXIC_ORB",
                weight: Weight::SourcePredicate("TOXIC_ORB"),
                payload: (),
            },
            Row {
                ordinal: 54,
                id: "FLAME_ORB",
                weight: Weight::SourcePredicate("FLAME_ORB"),
                payload: (),
            },
            Row {
                ordinal: 55,
                id: "FROSTBITE_ORB",
                weight: Weight::SourcePredicate("FROSTBITE_ORB"),
                payload: (),
            },
            Row {
                ordinal: 56,
                id: "MYSTICAL_ROCK",
                weight: Weight::SourcePredicate("MYSTICAL_ROCK"),
                payload: (),
            },
            Row {
                ordinal: 57,
                id: "REVIVER_SEED",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 58,
                id: "CANDY_JAR",
                weight: Weight::SourcePredicate("CANDY_JAR"),
                payload: (),
            },
            Row {
                ordinal: 59,
                id: "ATTACK_TYPE_BOOSTER",
                weight: Weight::Fixed(9),
                payload: (),
            },
            Row {
                ordinal: 60,
                id: "RARER_CANDY",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 61,
                id: "GOLDEN_PUNCH",
                weight: Weight::SourcePredicate("GOLDEN_PUNCH"),
                payload: (),
            },
            Row {
                ordinal: 62,
                id: "IV_SCANNER",
                weight: Weight::SourcePredicate("IV_SCANNER"),
                payload: (),
            },
            Row {
                ordinal: 63,
                id: "EXP_CHARM",
                weight: Weight::SourcePredicate("EXP_CHARM"),
                payload: (),
            },
            Row {
                ordinal: 64,
                id: "EXP_SHARE",
                weight: Weight::SourcePredicate("EXP_SHARE"),
                payload: (),
            },
            Row {
                ordinal: 65,
                id: "TERA_ORB",
                weight: Weight::SourcePredicate("TERA_ORB"),
                payload: (),
            },
            Row {
                ordinal: 66,
                id: "QUICK_CLAW",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 67,
                id: "WIDE_LENS",
                weight: Weight::Fixed(7),
                payload: (),
            },
            Row {
                ordinal: 68,
                id: "ER_CHILI_SAMPLE",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 69,
                id: "ER_COPPER_ROD",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 70,
                id: "ER_RUSTY_CLAW",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 71,
                id: "ER_SPIKED_KNUCKLES",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 72,
                id: "ER_LOADED_DICE",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 73,
                id: "ER_LUCKY_HEART",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 74,
                id: "ER_DEX_NAV",
                weight: Weight::Fixed(6),
                payload: (),
            },
            Row {
                ordinal: 75,
                id: "ER_POWER_HERB",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 76,
                id: "ER_LEARNERS_SHROOM",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 77,
                id: "ER_GREATER_ABILITY_CAPSULE",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 78,
                id: "MOVE_RANDOMIZER",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 79,
                id: "ER_EXPERT_BELT",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 80,
                id: "ER_HEAVY_DUTY_BOOTS",
                weight: Weight::SourcePredicate("ER_HEAVY_DUTY_BOOTS"),
                payload: (),
            },
            Row {
                ordinal: 81,
                id: "ER_AIR_BALLOON",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 82,
                id: "ER_SAFETY_GOGGLES",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 83,
                id: "ER_COVERT_CLOAK",
                weight: Weight::SourcePredicate("ER_COVERT_CLOAK"),
                payload: (),
            },
            Row {
                ordinal: 84,
                id: "ER_CLEAR_AMULET",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 85,
                id: "ER_ABILITY_SHIELD",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 86,
                id: "ER_THROAT_SPRAY",
                weight: Weight::SourcePredicate("ER_THROAT_SPRAY"),
                payload: (),
            },
            Row {
                ordinal: 87,
                id: "ER_PUNCHING_GLOVE",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 88,
                id: "ER_MUSCLE_BAND",
                weight: Weight::SourcePredicate("ER_MUSCLE_BAND"),
                payload: (),
            },
            Row {
                ordinal: 89,
                id: "ER_WISE_GLASSES",
                weight: Weight::SourcePredicate("ER_WISE_GLASSES"),
                payload: (),
            },
            Row {
                ordinal: 90,
                id: "ER_ZOOM_LENS",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 91,
                id: "ER_IRON_BALL",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 92,
                id: "ER_FLOAT_STONE",
                weight: Weight::SourcePredicate("ER_FLOAT_STONE"),
                payload: (),
            },
            Row {
                ordinal: 93,
                id: "ER_SMOKE_BALL",
                weight: Weight::SourcePredicate("ER_SMOKE_BALL"),
                payload: (),
            },
            Row {
                ordinal: 94,
                id: "ER_UTILITY_UMBRELLA",
                weight: Weight::SourcePredicate("ER_UTILITY_UMBRELLA"),
                payload: (),
            },
        ],
        vec![
            Row {
                ordinal: 95,
                id: "ROGUE_BALL",
                weight: Weight::SourcePredicate("ROGUE_BALL"),
                payload: (),
            },
            Row {
                ordinal: 96,
                id: "RELIC_GOLD",
                weight: Weight::SourcePredicate("RELIC_GOLD"),
                payload: (),
            },
            Row {
                ordinal: 97,
                id: "LEFTOVERS",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 98,
                id: "SHELL_BELL",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 99,
                id: "BERRY_POUCH",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 100,
                id: "GRIP_CLAW",
                weight: Weight::Fixed(5),
                payload: (),
            },
            Row {
                ordinal: 101,
                id: "SCOPE_LENS",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 102,
                id: "BATON",
                weight: Weight::Fixed(2),
                payload: (),
            },
            Row {
                ordinal: 103,
                id: "SOUL_DEW",
                weight: Weight::Fixed(7),
                payload: (),
            },
            Row {
                ordinal: 104,
                id: "CATCHING_CHARM",
                weight: Weight::SourcePredicate("CATCHING_CHARM"),
                payload: (),
            },
            Row {
                ordinal: 105,
                id: "ABILITY_CHARM",
                weight: Weight::SourcePredicate("ABILITY_CHARM"),
                payload: (),
            },
            Row {
                ordinal: 106,
                id: "ABILITY_RANDOMIZER",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 107,
                id: "MOVE_SLOT_EXPANDER",
                weight: Weight::Fixed(4),
                payload: (),
            },
            Row {
                ordinal: 108,
                id: "ER_GREATER_MOVE_RANDOMIZER",
                weight: Weight::SourcePredicate("ER_GREATER_MOVE_RANDOMIZER"),
                payload: (),
            },
            Row {
                ordinal: 109,
                id: "ER_OMNI_GEM",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 110,
                id: "ER_METRONOME_ITEM",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 111,
                id: "ER_BOOSTER_ENERGY",
                weight: Weight::SourcePredicate("ER_BOOSTER_ENERGY"),
                payload: (),
            },
            Row {
                ordinal: 112,
                id: "DAMAGE_CALCULATOR",
                weight: Weight::SourcePredicate("DAMAGE_CALCULATOR"),
                payload: (),
            },
            Row {
                ordinal: 113,
                id: "FOCUS_BAND",
                weight: Weight::Fixed(5),
                payload: (),
            },
            Row {
                ordinal: 114,
                id: "KINGS_ROCK",
                weight: Weight::Fixed(3),
                payload: (),
            },
            Row {
                ordinal: 115,
                id: "LOCK_CAPSULE",
                weight: Weight::SourcePredicate("LOCK_CAPSULE"),
                payload: (),
            },
            Row {
                ordinal: 116,
                id: "SUPER_EXP_CHARM",
                weight: Weight::SourcePredicate("SUPER_EXP_CHARM"),
                payload: (),
            },
            Row {
                ordinal: 117,
                id: "RARE_FORM_CHANGE_ITEM",
                weight: Weight::SourcePredicate("RARE_FORM_CHANGE_ITEM"),
                payload: (),
            },
            Row {
                ordinal: 118,
                id: "MEGA_BRACELET",
                weight: Weight::SourcePredicate("MEGA_BRACELET"),
                payload: (),
            },
            Row {
                ordinal: 119,
                id: "DYNAMAX_BAND",
                weight: Weight::SourcePredicate("DYNAMAX_BAND"),
                payload: (),
            },
            Row {
                ordinal: 120,
                id: "VOUCHER_PLUS",
                weight: Weight::SourcePredicate("VOUCHER_PLUS"),
                payload: (),
            },
        ],
        vec![
            Row {
                ordinal: 121,
                id: "MASTER_BALL",
                weight: Weight::SourcePredicate("MASTER_BALL"),
                payload: (),
            },
            Row {
                ordinal: 122,
                id: "SHINY_CHARM",
                weight: Weight::Fixed(14),
                payload: (),
            },
            Row {
                ordinal: 123,
                id: "HEALING_CHARM",
                weight: Weight::Fixed(18),
                payload: (),
            },
            Row {
                ordinal: 124,
                id: "MULTI_LENS",
                weight: Weight::Fixed(18),
                payload: (),
            },
            Row {
                ordinal: 125,
                id: "VOUCHER_PREMIUM",
                weight: Weight::SourcePredicate("VOUCHER_PREMIUM"),
                payload: (),
            },
            Row {
                ordinal: 126,
                id: "DNA_SPLICERS",
                weight: Weight::SourcePredicate("DNA_SPLICERS"),
                payload: (),
            },
            Row {
                ordinal: 127,
                id: "MINI_BLACK_HOLE",
                weight: Weight::SourcePredicate("MINI_BLACK_HOLE"),
                payload: (),
            },
            Row {
                ordinal: 128,
                id: "ER_GREATER_ABILITY_RANDOMIZER",
                weight: Weight::Fixed(2),
                payload: (),
            },
        ],
    ]
}
