/*
 * SPDX-FileCopyrightText: 2024-2026 Pagefault Games
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// =============================================================================
// ER Black Shiny (#349) — generated t4 sprite manifest.
//
// Keys are `${"back/" | ""}${speciesId}` for atlases that EXIST in er-assets
// under images/pokemon/black/ (generated by
// scripts/asset-tooling/black-shiny/generate_black_shinies.py per the pipeline
// in docs/design/black-shiny-sprite-pipeline.md, served via the jsDelivr
// redirect). A black shiny whose atlas isn't here yet falls back to the base
// sprite + the interim obsidian tint.
//
// PILOT BATCH (look approval): the species used by the four dev scenarios.
// The full roster batch lands after the maintainer signs off on the look.
// =============================================================================

export const ER_BLACK_SPRITES: ReadonlySet<string> = new Set([
  // front
  "39", // Jigglypuff
  "143", // Snorlax
  "268", // Cascoon
  "282", // Gardevoir
  "445", // Garchomp
  // back
  "back/39",
  "back/143",
  "back/268",
  "back/282",
  "back/445",
]);

/** The black atlas key for a species/back combo, or null if not generated. */
export function erBlackSpritePath(speciesId: number, back: boolean): string | null {
  const key = `${back ? "back/" : ""}${speciesId}`;
  return ER_BLACK_SPRITES.has(key) ? `black/${key}` : null;
}
