/*
 * SPDX-FileCopyrightText: 2024-2026 Pagefault Games
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// =============================================================================
// Elite Redux — corrective move-stat pass driven by ER C SOURCE (v2.65.3b).
//
// PROBLEM: the JSON dump at `vendor/elite-redux/v2.65beta.json` is the BETA
// snapshot. Many moves had stat retunes between the beta and the final
// v2.65.3b release (the ROM we actually ship against). The previous
// numeric-rebalance pass in `init-elite-redux-vanilla-rebalance.ts` reads
// from `er-moves.ts` (auto-generated from the beta JSON) and so applies
// stale values — e.g., it patches MoveId.POUND to pp=20 even though
// pokerogue's vanilla pp=35 already matches the ER C source.
//
// SOLUTION: this file loads the C-source-parsed JSON (produced by
// `scripts/elite-redux/parse_er_battle_moves.py`) and OVERWRITES the move
// stats with the authoritative values. Runs AFTER the JSON-based rebalance.
//
// Idempotent: writes are unconditional (idempotent by construction since
// the C source values are constants).
// =============================================================================

import { allMoves } from "#data/data-lists";
import { ER_FLAG_NAMES_LIST, ER_FLAG_TO_MOVE_FLAG } from "#data/elite-redux/er-flag-mapping";
import { ER_ID_MAP } from "#data/elite-redux/er-id-map";
import { ER_MOVES } from "#data/elite-redux/er-moves";
import type { Move } from "#data/moves/move";
import { MoveFlags } from "#enums/move-flags";
import type { MoveId } from "#enums/move-id";

// Embedded snapshot of the C-source-derived move stats — kept inline rather
// than as a separate JSON import to keep this self-contained. Generated via
// `python scripts/elite-redux/parse_er_battle_moves.py` and bundled here as
// a {moveConst → {power, accuracy, pp, chance}} map (only entries where the
// C source diverges from the JSON dump).
//
// To regenerate the full corrections list, run the audit script and replace
// this object. The map intentionally only contains moves where ER C source
// disagrees with the beta JSON dump.
const C_SOURCE_OVERRIDES: ReadonlyMap<
  string,
  {
    power?: number;
    accuracy?: number;
    pp?: number;
    chance?: number;
  }
> = new Map([
  // Auto-generated by er-move-diff-audit. 312 entries — only moves where the
  // beta JSON dump values diverge from the v2.65.3b ER C source.
  // Regenerate with: ER_SCENARIO=1 pnpm test test/tests/elite-redux/integration/er-move-diff-audit.test.ts
  // then run scripts/elite-redux/generate_c_source_overrides.py
  ["MOVE_POUND", { pp: 35 }],
  // MANUAL Nextdex override (do NOT regenerate away): the v2.65.3b C source had
  // Karate Chop at 60/–/25, but the live Elite Redux Nextdex shows 90 / 100 / 10
  // (Fighting, high crit). The Nextdex is the canonical balance source the
  // player base uses, so pin to it.
  ["MOVE_KARATE_CHOP", { power: 90, accuracy: 100, pp: 10 }],
  ["MOVE_DOUBLE_SLAP", { chance: 0 }],
  ["MOVE_COMET_PUNCH", { power: 25, pp: 15 }],
  ["MOVE_FIRE_PUNCH", { power: 75 }],
  ["MOVE_ICE_PUNCH", { power: 75 }],
  ["MOVE_THUNDER_PUNCH", { power: 75 }],
  ["MOVE_SCRATCH", { pp: 35 }],
  ["MOVE_VISE_GRIP", { power: 70, accuracy: 100, pp: 30 }],
  ["MOVE_GUILLOTINE", { chance: 0 }],
  ["MOVE_RAZOR_WIND", { power: 90 }],
  ["MOVE_CUT", { chance: 0 }],
  ["MOVE_WING_ATTACK", { power: 80 }],
  ["MOVE_WHIRLWIND", { pp: 20 }],
  ["MOVE_BIND", { accuracy: 90 }],
  ["MOVE_SLAM", { power: 90, pp: 20 }],
  ["MOVE_VINE_WHIP", { power: 75, pp: 20 }],
  ["MOVE_DOUBLE_KICK", { power: 30, pp: 30 }],
  ["MOVE_ROLLING_KICK", { power: 60, accuracy: 85 }],
  ["MOVE_HEADBUTT", { power: 70 }],
  ["MOVE_HORN_ATTACK", { power: 80, pp: 25, chance: 0 }],
  ["MOVE_HORN_DRILL", { power: 120, accuracy: 90, chance: 0 }],
  ["MOVE_TACKLE", { pp: 35 }],
  ["MOVE_WRAP", { accuracy: 90 }],
  ["MOVE_TAKE_DOWN", { power: 95, chance: 0 }],
  ["MOVE_THRASH", { power: 120, pp: 10 }],
  ["MOVE_DOUBLE_EDGE", { power: 120, pp: 15 }],
  ["MOVE_TAIL_WHIP", { pp: 30 }],
  ["MOVE_POISON_STING", { chance: 30 }],
  ["MOVE_LEER", { pp: 30 }],
  ["MOVE_BITE", { pp: 25 }],
  // GROWL is rebalanced into a Special damaging move (see vanilla-move-patches)
  // whose Attack drop is now a *secondary* effect gated by `move.chance`. The
  // ROM's secondaryEffectChance is 0 (the drop is its PRIMARY effect there), but
  // copying that 0 onto the converted damaging move would make the drop never
  // fire. ER's move data lists effectChance 100, so the drop is guaranteed.
  ["MOVE_GROWL", { pp: 40, chance: 100 }],
  ["MOVE_SING", { accuracy: 55 }],
  ["MOVE_SUPERSONIC", { accuracy: 55 }],
  ["MOVE_SONIC_BOOM", { power: 1, accuracy: 90 }],
  ["MOVE_ACID", { power: 40, pp: 30, chance: 10 }],
  ["MOVE_EMBER", { power: 40, pp: 25, chance: 10 }],
  ["MOVE_MIST", { pp: 30 }],
  ["MOVE_WATER_GUN", { pp: 25, chance: 0 }],
  ["MOVE_HYDRO_PUMP", { accuracy: 80, chance: 0 }],
  ["MOVE_SURF", { chance: 0 }],
  ["MOVE_BLIZZARD", { accuracy: 80, chance: 10 }],
  ["MOVE_PSYBEAM", { chance: 10 }],
  // ER turns Bubble Beam into a 25-power Water pulse that hits 2–5 times
  // (Mega Launcher–boosted; PULSE_MOVE flag added below). The multi-hit attr +
  // removal of the vanilla Speed-drop are wired in the move-patch table.
  ["MOVE_BUBBLE_BEAM", { power: 25 }],
  ["MOVE_HYPER_BEAM", { accuracy: 90 }],
  ["MOVE_DRILL_PECK", { chance: 0 }],
  ["MOVE_SUBMISSION", { power: 150, accuracy: 80, pp: 15 }],
  ["MOVE_SEISMIC_TOSS", { pp: 20 }],
  ["MOVE_STRENGTH", { power: 100, pp: 10 }],
  ["MOVE_ABSORB", { power: 35, pp: 25, chance: 0 }],
  ["MOVE_MEGA_DRAIN", { power: 60 }],
  ["MOVE_RAZOR_LEAF", { pp: 25, chance: 100 }],
  ["MOVE_POISON_POWDER", { pp: 35 }],
  ["MOVE_STUN_SPORE", { accuracy: 75, pp: 30 }],
  ["MOVE_PETAL_DANCE", { pp: 10 }],
  ["MOVE_STRING_SHOT", { accuracy: 95, pp: 40 }],
  ["MOVE_DRAGON_RAGE", { power: 1, pp: 10 }],
  ["MOVE_THUNDER_SHOCK", { power: 40, pp: 30, chance: 10 }],
  ["MOVE_THUNDER_WAVE", { pp: 20 }],
  ["MOVE_THUNDER", { accuracy: 75, pp: 10 }],
  ["MOVE_ROCK_THROW", { power: 50, pp: 15 }],
  ["MOVE_CONFUSION", { pp: 25, chance: 10 }],
  ["MOVE_PSYCHIC", { chance: 10 }],
  ["MOVE_MEDITATE", { pp: 40 }],
  ["MOVE_AGILITY", { pp: 30 }],
  ["MOVE_QUICK_ATTACK", { pp: 30 }],
  ["MOVE_RAGE", { power: 40, pp: 20, chance: 0 }],
  ["MOVE_SCREECH", { pp: 40 }],
  ["MOVE_RECOVER", { pp: 10 }],
  ["MOVE_HARDEN", { pp: 30 }],
  ["MOVE_WITHDRAW", { pp: 40 }],
  ["MOVE_DEFENSE_CURL", { pp: 40 }],
  ["MOVE_LIGHT_SCREEN", { pp: 30 }],
  ["MOVE_HAZE", { pp: 30 }],
  ["MOVE_FOCUS_ENERGY", { pp: 30 }],
  ["MOVE_EGG_BOMB", { accuracy: 90, chance: 10 }],
  ["MOVE_LICK", { pp: 30 }],
  ["MOVE_SLUDGE", { power: 65 }],
  ["MOVE_BONE_CLUB", { power: 75, accuracy: 95 }],
  ["MOVE_FIRE_BLAST", { chance: 20 }],
  ["MOVE_SWIFT", { power: 60, pp: 20 }],
  ["MOVE_SKULL_BASH", { power: 130 }],
  ["MOVE_CONSTRICT", { power: 55 }],
  ["MOVE_KINESIS", { accuracy: 80, pp: 15 }],
  ["MOVE_SOFT_BOILED", { pp: 10 }],
  ["MOVE_GLARE", { pp: 30 }],
  ["MOVE_POISON_GAS", { accuracy: 90, pp: 40, chance: 0 }],
  ["MOVE_BARRAGE", { accuracy: 85, pp: 20 }],
  ["MOVE_BUBBLE", { power: 60 }],
  ["MOVE_DIZZY_PUNCH", { power: 70 }],
  ["MOVE_PSYWAVE", { chance: 30 }],
  ["MOVE_SPLASH", { pp: 40, chance: 0 }],
  ["MOVE_CRABHAMMER", { accuracy: 90, chance: 0 }],
  ["MOVE_FURY_SWIPES", { power: 20 }],
  ["MOVE_BONEMERANG", { power: 50 }],
  ["MOVE_HYPER_FANG", { power: 75 }],
  ["MOVE_SHARPEN", { pp: 30 }],
  ["MOVE_CONVERSION", { pp: 30 }],
  ["MOVE_SLASH", { power: 70, pp: 20, chance: 0 }],
  ["MOVE_TRIPLE_KICK", { power: 25 }],
  ["MOVE_THIEF", { pp: 25 }],
  ["MOVE_MIND_READER", { pp: 5 }],
  ["MOVE_NIGHTMARE", { pp: 15, chance: 0 }],
  ["MOVE_FLAME_WHEEL", { power: 65, pp: 25 }],
  ["MOVE_SNORE", { power: 50 }],
  ["MOVE_FLAIL", { power: 1, pp: 15 }],
  ["MOVE_CONVERSION_2", { pp: 30 }],
  ["MOVE_COTTON_SPORE", { pp: 40 }],
  ["MOVE_REVERSAL", { power: 1, pp: 15 }],
  ["MOVE_POWDER_SNOW", { power: 40, pp: 25, chance: 10 }],
  ["MOVE_MACH_PUNCH", { pp: 30 }],
  ["MOVE_FEINT_ATTACK", { power: 60, pp: 20 }],
  ["MOVE_MUD_SLAP", { power: 20 }],
  ["MOVE_OCTAZOOKA", { power: 100 }],
  ["MOVE_FORESIGHT", { pp: 40 }],
  ["MOVE_DETECT", { pp: 5 }],
  ["MOVE_OUTRAGE", { pp: 10 }],
  ["MOVE_ENDURE", { pp: 10 }],
  ["MOVE_ROLLOUT", { power: 30, accuracy: 90, pp: 20 }],
  ["MOVE_FALSE_SWIPE", { power: 80, pp: 40, chance: 0 }],
  ["MOVE_MILK_DRINK", { pp: 10 }],
  ["MOVE_FURY_CUTTER", { power: 40, accuracy: 95, pp: 20 }],
  ["MOVE_RETURN", { power: 95 }],
  ["MOVE_PRESENT", { power: 1, accuracy: 90 }],
  ["MOVE_FRUSTRATION", { power: 95, pp: 20 }],
  ["MOVE_SAFEGUARD", { pp: 25 }],
  ["MOVE_MAGNITUDE", { pp: 30 }],
  ["MOVE_DYNAMIC_PUNCH", { power: 100 }],
  ["MOVE_MEGAHORN", { chance: 0 }],
  ["MOVE_DRAGON_BREATH", { power: 70, chance: 30 }],
  ["MOVE_BATON_PASS", { pp: 40 }],
  ["MOVE_RAPID_SPIN", { pp: 40, chance: 0 }],
  ["MOVE_IRON_TAIL", { accuracy: 90, pp: 15, chance: 30 }],
  ["MOVE_VITAL_THROW", { power: 70 }],
  ["MOVE_HIDDEN_POWER", { power: 70 }],
  ["MOVE_CROSS_CHOP", { power: 100, accuracy: 80, pp: 5 }],
  ["MOVE_TWISTER", { accuracy: 100, chance: 20 }],
  ["MOVE_RAIN_DANCE", { pp: 5 }],
  ["MOVE_SUNNY_DAY", { pp: 5 }],
  ["MOVE_CRUNCH", { power: 80 }],
  ["MOVE_SHADOW_BALL", { power: 85 }],
  ["MOVE_WHIRLPOOL", { chance: 100 }],
  ["MOVE_UPROAR", { power: 90, pp: 10 }],
  ["MOVE_STOCKPILE", { pp: 20 }],
  ["MOVE_SPIT_UP", { power: 1, pp: 10 }],
  ["MOVE_SWALLOW", { pp: 10 }],
  ["MOVE_WILL_O_WISP", { accuracy: 85, pp: 15 }],
  ["MOVE_SMELLING_SALTS", { power: 70 }],
  ["MOVE_NATURE_POWER", { pp: 20 }],
  ["MOVE_RECYCLE", { pp: 10 }],
  ["MOVE_REFRESH", { pp: 20 }],
  ["MOVE_SECRET_POWER", { power: 70 }],
  ["MOVE_DIVE", { chance: 0 }],
  ["MOVE_ARM_THRUST", { power: 20, pp: 20 }],
  ["MOVE_CAMOUFLAGE", { accuracy: 100, pp: 20 }],
  ["MOVE_LUSTER_PURGE", { power: 95 }],
  ["MOVE_MIST_BALL", { power: 95 }],
  ["MOVE_ICE_BALL", { power: 30, accuracy: 90, pp: 20 }],
  ["MOVE_NEEDLE_ARM", { power: 95, pp: 15, chance: 30 }],
  ["MOVE_SLACK_OFF", { pp: 10 }],
  ["MOVE_HYPER_VOICE", { power: 90 }],
  ["MOVE_BLAST_BURN", { power: 150, accuracy: 90 }],
  ["MOVE_HYDRO_CANNON", { power: 150, accuracy: 90 }],
  ["MOVE_ASTONISH", { pp: 15, chance: 100 }], // ER: Ghost Fake Out — guaranteed first-turn flinch (#221)
  ["MOVE_AIR_CUTTER", { power: 70, pp: 25 }],
  ["MOVE_ODOR_SLEUTH", { pp: 40 }],
  ["MOVE_ROCK_TOMB", { power: 60 }],
  ["MOVE_METAL_SOUND", { pp: 40 }],
  ["MOVE_GRASS_WHISTLE", { accuracy: 55 }],
  ["MOVE_WATER_SPOUT", { chance: 0 }],
  ["MOVE_SIGNAL_BEAM", { power: 75, chance: 10 }],
  ["MOVE_EXTRASENSORY", { pp: 20 }],
  ["MOVE_SKY_UPPERCUT", { power: 95 }],
  ["MOVE_MUDDY_WATER", { power: 90 }],
  ["MOVE_BULLET_SEED", { pp: 30 }],
  ["MOVE_ICICLE_SPEAR", { pp: 30 }],
  ["MOVE_HOWL", { pp: 40 }],
  ["MOVE_DRAGON_CLAW", { power: 80, chance: 0 }],
  ["MOVE_FRENZY_PLANT", { power: 150, accuracy: 90 }],
  ["MOVE_BOUNCE", { power: 85, accuracy: 90, pp: 5 }],
  ["MOVE_POISON_TAIL", { power: 80, pp: 25, chance: 30 }],
  ["MOVE_COVET", { pp: 25 }],
  ["MOVE_VOLT_TACKLE", { pp: 15 }],
  ["MOVE_MAGICAL_LEAF", { power: 60 }],
  ["MOVE_LEAF_BLADE", { chance: 0 }],
  ["MOVE_ROOST", { pp: 10 }],
  ["MOVE_MIRACLE_EYE", { pp: 40 }],
  ["MOVE_WAKE_UP_SLAP", { power: 80 }],
  ["MOVE_BRINE", { power: 65, pp: 15 }],
  ["MOVE_NATURAL_GIFT", { chance: 0 }],
  ["MOVE_FEINT", { power: 30 }],
  ["MOVE_ACUPRESSURE", { pp: 30 }],
  ["MOVE_PAYBACK", { power: 50 }],
  ["MOVE_ASSURANCE", { power: 60 }],
  ["MOVE_FLING", { power: 1 }],
  ["MOVE_TRUMP_CARD", { pp: 5 }],
  ["MOVE_WRING_OUT", { pp: 5 }],
  ["MOVE_LUCKY_CHANT", { pp: 30 }],
  ["MOVE_POWER_SWAP", { chance: 0 }],
  ["MOVE_GUARD_SWAP", { chance: 0 }],
  ["MOVE_PUNISHMENT", { power: 60, pp: 5 }],
  ["MOVE_FLARE_BLITZ", { pp: 15 }],
  ["MOVE_FORCE_PALM", { power: 60, pp: 15, chance: 30 }],
  ["MOVE_AURA_SPHERE", { power: 80 }],
  ["MOVE_NIGHT_SLASH", { power: 70, chance: 0 }],
  ["MOVE_AQUA_TAIL", { power: 95 }],
  ["MOVE_AIR_SLASH", { power: 75 }],
  ["MOVE_X_SCISSOR", { chance: 0 }],
  ["MOVE_BUG_BUZZ", { chance: 10 }],
  ["MOVE_DRAGON_RUSH", { power: 95, accuracy: 95 }],
  ["MOVE_VACUUM_WAVE", { pp: 30 }],
  ["MOVE_FOCUS_BLAST", { accuracy: 70, chance: 10 }],
  ["MOVE_BRAVE_BIRD", { pp: 15 }],
  ["MOVE_GIGA_IMPACT", { accuracy: 90 }],
  ["MOVE_BULLET_PUNCH", { pp: 30 }],
  ["MOVE_AVALANCHE", { power: 60 }],
  ["MOVE_ICE_SHARD", { pp: 30 }],
  ["MOVE_SHADOW_CLAW", { chance: 0 }],
  ["MOVE_THUNDER_FANG", { power: 70 }],
  ["MOVE_ICE_FANG", { power: 70 }],
  ["MOVE_FIRE_FANG", { power: 70 }],
  ["MOVE_SHADOW_SNEAK", { pp: 30 }],
  ["MOVE_MUD_BOMB", { power: 65, pp: 15, chance: 30 }],
  ["MOVE_PSYCHO_CUT", { power: 70, chance: 0 }],
  ["MOVE_ZEN_HEADBUTT", { accuracy: 95, chance: 20 }],
  ["MOVE_MIRROR_SHOT", { accuracy: 85, chance: 30 }],
  ["MOVE_ROCK_CLIMB", { power: 85, chance: 20 }],
  ["MOVE_ROCK_WRECKER", { power: 150, accuracy: 90 }],
  ["MOVE_CROSS_POISON", { power: 90, pp: 15 }],
  ["MOVE_MAGNET_BOMB", { power: 60 }],
  ["MOVE_STONE_EDGE", { accuracy: 85, pp: 5, chance: 0 }],
  ["MOVE_JUDGMENT", { power: 100, pp: 10 }],
  ["MOVE_WOOD_HAMMER", { pp: 15 }],
  ["MOVE_HEAL_ORDER", { pp: 10 }],
  ["MOVE_DOUBLE_HIT", { power: 35 }],
  ["MOVE_CRUSH_GRIP", { power: 1 }],
  ["MOVE_OMINOUS_WIND", { power: 60 }],
  ["MOVE_SHADOW_FORCE", { chance: 0 }],
  ["MOVE_QUIVER_DANCE", { pp: 20 }],
  ["MOVE_SYNCHRONOISE", { power: 120 }],
  ["MOVE_COIL", { pp: 20 }],
  ["MOVE_ROUND", { chance: 0 }],
  ["MOVE_ECHOED_VOICE", { power: 40, accuracy: 100 }],
  ["MOVE_CHIP_AWAY", { chance: 0 }],
  ["MOVE_QUICK_GUARD", { pp: 15 }],
  ["MOVE_SCALD", { power: 80 }],
  ["MOVE_QUASH", { pp: 15 }],
  ["MOVE_ACROBATICS", { power: 55 }],
  ["MOVE_RETALIATE", { power: 75, pp: 5 }],
  ["MOVE_WATER_PLEDGE", { chance: 0 }],
  ["MOVE_FIRE_PLEDGE", { chance: 0 }],
  ["MOVE_GRASS_PLEDGE", { chance: 0 }],
  ["MOVE_STRUGGLE_BUG", { power: 50, pp: 20 }],
  ["MOVE_BULLDOZE", { power: 60 }],
  ["MOVE_WORK_UP", { pp: 30 }],
  ["MOVE_ELECTROWEB", { power: 55 }],
  ["MOVE_DRILL_RUN", { chance: 0 }],
  ["MOVE_HEART_STAMP", { power: 60, pp: 25 }],
  ["MOVE_LEAF_TORNADO", { chance: 50 }],
  ["MOVE_STEAMROLLER", { power: 65, pp: 20 }],
  ["MOVE_NIGHT_DAZE", { chance: 0 }],
  ["MOVE_HURRICANE", { accuracy: 75 }],
  ["MOVE_HEAD_CHARGE", { power: 120, pp: 15 }],
  ["MOVE_RELIC_SONG", { power: 85 }],
  ["MOVE_SNARL", { power: 55 }],
  ["MOVE_ICICLE_CRASH", { chance: 30 }],
  ["MOVE_V_CREATE", { accuracy: 95 }],
  ["MOVE_BELCH", { pp: 10 }],
  ["MOVE_FELL_STINGER", { pp: 25 }],
  ["MOVE_NOBLE_ROAR", { pp: 30 }],
  ["MOVE_ION_DELUGE", { pp: 25 }],
  ["MOVE_PETAL_BLIZZARD", { power: 90 }],
  ["MOVE_ELECTRIFY", { pp: 20 }],
  ["MOVE_MOONBLAST", { power: 95, chance: 30 }],
  ["MOVE_STEAM_ERUPTION", { accuracy: 95 }],
  ["MOVE_WATER_SHURIKEN", { power: 15 }],
  ["MOVE_AROMATIC_MIST", { pp: 20 }],
  ["MOVE_HAPPY_HOUR", { pp: 30 }],
  ["MOVE_CELEBRATE", { pp: 40 }],
  ["MOVE_HOLD_HANDS", { pp: 40 }],
  ["MOVE_BABY_DOLL_EYES", { pp: 30 }],
  ["MOVE_HOLD_BACK", { power: 40, pp: 40, chance: 0 }],
  ["MOVE_LANDS_WRATH", { power: 90 }],
  ["MOVE_SHORE_UP", { pp: 10 }],
  ["MOVE_FIRST_IMPRESSION", { power: 90, chance: 0 }],
  ["MOVE_SPIRIT_SHACKLE", { power: 90 }],
  ["MOVE_STRENGTH_SAP", { pp: 10 }],
  ["MOVE_LEAFAGE", { pp: 40 }],
  ["MOVE_LASER_FOCUS", { pp: 30 }],
  ["MOVE_GEAR_UP", { pp: 20 }],
  ["MOVE_THROAT_CHOP", { chance: 0 }],
  ["MOVE_LUNGE", { power: 80 }],
  ["MOVE_SMART_STRIKE", { power: 70 }],
  ["MOVE_BRUTAL_SWING", { power: 60 }],
  ["MOVE_PSYCHIC_FANGS", { power: 80 }],
  ["MOVE_ACCELEROCK", { pp: 20 }],
  ["MOVE_PRISMATIC_LASER", { power: 160 }],
  ["MOVE_SUNSTEEL_STRIKE", { power: 100 }],
  ["MOVE_MOONGEIST_BEAM", { power: 100 }],
  ["MOVE_ZING_ZAP", { pp: 10 }],
  ["MOVE_NATURES_MADNESS", { accuracy: 90, pp: 10 }],
  ["MOVE_MIND_BLOWN", { chance: 0 }],
  ["MOVE_ZIPPY_ZAP", { chance: 100 }],
  ["MOVE_FLOATY_FALL", { accuracy: 95 }],
  ["MOVE_PIKA_PAPOW", { power: 1, pp: 20 }],
  ["MOVE_GLITZY_GLOW", { accuracy: 95 }],
  ["MOVE_BADDY_BAD", { accuracy: 95 }],
  ["MOVE_VEEVEE_VOLLEY", { power: 1, pp: 20 }],
  ["MOVE_BOLT_BEAK", { power: 85 }],
  ["MOVE_FISHIOUS_REND", { power: 85 }],
  ["MOVE_BRANCH_POKE", { pp: 40 }],
  ["MOVE_METEOR_ASSAULT", { power: 150 }],
  ["MOVE_ETERNABEAM", { power: 160, accuracy: 90 }],
  ["MOVE_STEEL_ROLLER", { power: 130, pp: 5 }],
  ["MOVE_MISTY_EXPLOSION", { power: 100 }],
  ["MOVE_TERRAIN_PULSE", { pp: 10 }],
  ["MOVE_SKITTER_SMACK", { power: 70, accuracy: 90, pp: 10 }],
  ["MOVE_BURNING_JEALOUSY", { chance: 50 }],
  ["MOVE_LASH_OUT", { power: 75, pp: 5 }],
  ["MOVE_CORROSIVE_GAS", { pp: 40, chance: 0 }],
  ["MOVE_DUAL_WINGBEAT", { accuracy: 95 }],
  ["MOVE_WICKED_BLOW", { power: 70 }],
  ["MOVE_GLACIAL_LANCE", { power: 130 }],
  ["MOVE_EERIE_SPELL", { power: 80, accuracy: 100, pp: 5, chance: 0 }],
  ["MOVE_DEATHROLL", { accuracy: 95 }],
  ["MOVE_EXCALIBUR", { chance: 0 }],
  ["MOVE_AQUA_FANG", { power: 80, chance: 10 }],
  ["MOVE_WAVE_CRASH", { pp: 15, chance: 0 }],
  ["MOVE_SMITE", { chance: 100 }],
]);

// =============================================================================
// FLAG corrections — moves missing ER-gameplay-relevant flags
// (BITING_MOVE, PUNCHING_MOVE, SLICING_MOVE, KICKING_MOVE, PULSE_MOVE,
// SOUND_BASED, BALLBOMB_MOVE, POWDER_MOVE, AIR_BASED, BONE_BASED,
// HORN_BASED, FIELD_BASED, WEATHER_BASED, RECKLESS_MOVE, DANCE_MOVE).
// Source: er-battle-moves.json (parsed from v2.65.3b C source).
// =============================================================================
const C_SOURCE_FLAG_PATCHES: ReadonlyMap<string, MoveFlags> = new Map([
  ["MOVE_FLY", MoveFlags.FIELD_BASED],
  ["MOVE_STOMP", MoveFlags.KICKING_MOVE],
  ["MOVE_DOUBLE_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_MEGA_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_JUMP_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_ROLLING_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_HEADBUTT", MoveFlags.FIELD_BASED],
  ["MOVE_TWINEEDLE", MoveFlags.MAKES_CONTACT],
  ["MOVE_WATER_GUN", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_HYDRO_PUMP", MoveFlags.PULSE_MOVE],
  ["MOVE_SURF", MoveFlags.FIELD_BASED],
  ["MOVE_ICE_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_BLIZZARD", MoveFlags.WEATHER_BASED],
  ["MOVE_PSYBEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_BUBBLE_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_AURORA_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_HYPER_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_LOW_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_SOLAR_BEAM", MoveFlags.WEATHER_BASED | MoveFlags.PULSE_MOVE],
  ["MOVE_THUNDER", MoveFlags.WEATHER_BASED],
  ["MOVE_WATERFALL", MoveFlags.FIELD_BASED],
  ["MOVE_SPIKE_CANNON", MoveFlags.BALLBOMB_MOVE],
  ["MOVE_HIGH_JUMP_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_LEECH_LIFE", MoveFlags.BITING_MOVE],
  ["MOVE_SUPER_FANG", MoveFlags.BITING_MOVE],
  ["MOVE_TRIPLE_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_OCTAZOOKA", MoveFlags.PULSE_MOVE],
  ["MOVE_ZAP_CANNON", MoveFlags.PULSE_MOVE],
  ["MOVE_FALSE_SWIPE", MoveFlags.SLICING_MOVE],
  ["MOVE_WHIRLPOOL", MoveFlags.FIELD_BASED],
  ["MOVE_ERUPTION", MoveFlags.PULSE_MOVE],
  ["MOVE_SECRET_POWER", MoveFlags.FIELD_BASED],
  ["MOVE_DIVE", MoveFlags.FIELD_BASED],
  ["MOVE_BLAZE_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_NEEDLE_ARM", MoveFlags.PUNCHING_MOVE],
  ["MOVE_HYDRO_CANNON", MoveFlags.PULSE_MOVE],
  ["MOVE_WEATHER_BALL", MoveFlags.WEATHER_BASED],
  ["MOVE_WATER_SPOUT", MoveFlags.PULSE_MOVE],
  ["MOVE_SIGNAL_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_DRAGON_CLAW", MoveFlags.SLICING_MOVE],
  ["MOVE_FRENZY_PLANT", MoveFlags.PULSE_MOVE],
  ["MOVE_MUD_SHOT", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_PLUCK", MoveFlags.BITING_MOVE],
  ["MOVE_CLOSE_COMBAT", MoveFlags.PUNCHING_MOVE],
  ["MOVE_POISON_JAB", MoveFlags.PUNCHING_MOVE],
  ["MOVE_VACUUM_WAVE", MoveFlags.PULSE_MOVE],
  ["MOVE_FOCUS_BLAST", MoveFlags.PULSE_MOVE],
  ["MOVE_SHADOW_CLAW", MoveFlags.SLICING_MOVE],
  ["MOVE_ZEN_HEADBUTT", MoveFlags.FIELD_BASED],
  ["MOVE_MIRROR_SHOT", MoveFlags.PULSE_MOVE],
  ["MOVE_FLASH_CANNON", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_GUNK_SHOT", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_STONE_EDGE", MoveFlags.SLICING_MOVE],
  ["MOVE_BUG_BITE", MoveFlags.BITING_MOVE],
  ["MOVE_CHARGE_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_ROAR_OF_TIME", MoveFlags.SOUND_BASED],
  ["MOVE_FLAME_BURST", MoveFlags.PULSE_MOVE],
  ["MOVE_INFERNO", MoveFlags.PULSE_MOVE],
  ["MOVE_DRILL_RUN", MoveFlags.HORN_BASED],
  ["MOVE_DUAL_CHOP", MoveFlags.SLICING_MOVE],
  ["MOVE_HURRICANE", MoveFlags.WEATHER_BASED],
  ["MOVE_SEARING_SHOT", MoveFlags.PULSE_MOVE],
  ["MOVE_PARTING_SHOT", MoveFlags.PULSE_MOVE],
  ["MOVE_STEAM_ERUPTION", MoveFlags.PULSE_MOVE],
  ["MOVE_HIGH_HORSEPOWER", MoveFlags.KICKING_MOVE],
  ["MOVE_SOLAR_BLADE", MoveFlags.WEATHER_BASED],
  ["MOVE_ANCHOR_SHOT", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_TROP_KICK", MoveFlags.KICKING_MOVE],
  ["MOVE_FLEUR_CANNON", MoveFlags.PULSE_MOVE],
  ["MOVE_PSYCHIC_FANGS", MoveFlags.PUNCHING_MOVE],
  ["MOVE_SUNSTEEL_STRIKE", MoveFlags.PULSE_MOVE],
  ["MOVE_MOONGEIST_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_NATURES_MADNESS", MoveFlags.MAKES_CONTACT],
  ["MOVE_PHOTON_GEYSER", MoveFlags.PULSE_MOVE],
  ["MOVE_DYNAMAX_CANNON", MoveFlags.PULSE_MOVE],
  ["MOVE_SNIPE_SHOT", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_TAR_SHOT", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_PYRO_BALL", MoveFlags.KICKING_MOVE],
  ["MOVE_BREAKING_SWIPE", MoveFlags.SLICING_MOVE],
  ["MOVE_METEOR_ASSAULT", MoveFlags.SLICING_MOVE],
  ["MOVE_ETERNABEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_STEEL_BEAM", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_SCALE_SHOT", MoveFlags.PULSE_MOVE | MoveFlags.BALLBOMB_MOVE],
  ["MOVE_METEOR_BEAM", MoveFlags.PULSE_MOVE],
  ["MOVE_TRIPLE_AXEL", MoveFlags.KICKING_MOVE],
  ["MOVE_DRAGON_ENERGY", MoveFlags.PULSE_MOVE],
  ["MOVE_THUNDEROUS_KICK", MoveFlags.KICKING_MOVE],
]);

export interface CSourceCorrectionResult {
  movesPatched: number;
  flagsPatched: number;
  movesMissing: number;
}

/**
 * Repair vanilla ER move ids that the build mapped to the WRONG pokerogue move.
 *
 * Two failure modes from the beta-JSON build:
 *   1. Newer (Gen-9) moves like Aqua Cutter got an id pointing at an empty slot
 *      (a "hole") instead of their real, implemented `MoveId`.
 *   2. A scrambled gen8/9 block where ER ids landed on the WRONG built move
 *      (e.g. Kowtow Cleave -> Blood Moon, Axe Kick -> Trailblaze) — so the move
 *      silently received another move's rebalance + effects (#151).
 *
 * Both are repaired the same way: `allMoves` is correctly id-indexed, so we
 * resolve each ER move's real id by its display name and repoint the ER id when
 * it currently lands on a different move (or a hole). Only ER moves whose name
 * matches a built pokerogue move are touched; correctly-mapped moves and moves
 * with no name-match (e.g. ER-renamed) are left untouched. Idempotent.
 *
 * MUST run BEFORE {@linkcode initEliteReduxVanillaRebalance} / move-patches /
 * movesets so every downstream consumer sees the corrected id-map and applies
 * stats + effects to the right move. (Also invoked from
 * {@linkcode initEliteReduxCSourceCorrections} as an idempotent safety net.)
 *
 * @returns the number of ER move ids repointed this run.
 */
export function remapEliteReduxMoveIdsByName(): number {
  const movesMap = ER_ID_MAP.moves as Record<number, number>;
  const idByName = new Map<string, number>();
  for (const mv of allMoves) {
    if (mv !== undefined) {
      idByName.set(mv.name.toLowerCase(), mv.id);
    }
  }
  let remapped = 0;
  for (const drf of ER_MOVES) {
    const current = movesMap[drf.id];
    if (current === undefined || current >= 5000) {
      continue; // custom or unmapped
    }
    const realId = drf.name ? idByName.get(drf.name.toLowerCase()) : undefined;
    // Repoint whenever the ER move resolves (by name) to a different real move
    // than its current mapping — covers both holes and wrong-built-move landings.
    if (realId !== undefined && realId !== current) {
      movesMap[drf.id] = realId;
      remapped++;
    }
  }
  if (remapped > 0) {
    console.info(`[er-csrc] remapped ${remapped} ER moves to their real MoveIds (by name)`);
  }
  return remapped;
}

/**
 * Apply C-source corrective overrides to {@linkcode allMoves}.
 *
 * Call AFTER {@linkcode initEliteReduxVanillaRebalance} so the JSON-derived
 * (stale) values are written first and then corrected here.
 */
export function initEliteReduxCSourceCorrections(): CSourceCorrectionResult {
  const result: CSourceCorrectionResult = {
    movesPatched: 0,
    flagsPatched: 0,
    movesMissing: 0,
  };

  // Idempotent safety net: ensure the move id-map is name-correct here too, so
  // tests that invoke only this function (and any path that reaches corrections
  // before the early remap) still observe the fixed mappings.
  remapEliteReduxMoveIdsByName();

  // ---------------------------------------------------------------------------
  // Apply each ER move's FULL ROM flag set onto its built move. The ROM stores
  // flags as numeric indices into ER_FLAG_NAMES_LIST; we map each to its
  // pokerogue MoveFlag and OR it on (additive — never clears a pokerogue flag).
  // The hand-curated vanilla-move-patches only covered a subset, leaving ~140
  // flag bits (Air/Throw/Horn/Hammer-Based, contact, sound, …) missing — which
  // silently broke ER flag-gated abilities (e.g. wing/throw/horn boosters) and
  // contact/sound interactions on many moves. This guarantees full coverage.
  // ---------------------------------------------------------------------------
  {
    const movesMap = ER_ID_MAP.moves as Record<number, number>;
    let movesFlagged = 0;
    for (const drf of ER_MOVES) {
      const pkrgId = movesMap[drf.id];
      if (pkrgId === undefined) {
        continue;
      }
      const move = allMoves[pkrgId];
      if (move === undefined) {
        continue;
      }
      let bits = 0;
      for (const idx of (drf as { flags?: number[] }).flags ?? []) {
        const name = ER_FLAG_NAMES_LIST[idx];
        const mf = name === undefined ? undefined : ER_FLAG_TO_MOVE_FLAG[name];
        if (mf != null) {
          bits |= mf;
        }
      }
      if (bits !== 0) {
        const target = move as unknown as { flags: number };
        if ((target.flags & bits) !== bits) {
          target.flags |= bits;
          movesFlagged++;
        }
      }
    }
    if (movesFlagged > 0) {
      console.info(`[er-csrc] applied ROM flag sets to ${movesFlagged} moves (full flag coverage)`);
    }
  }

  // Build moveConst → pokerogue MoveId map.
  const constToPkrgId = new Map<string, MoveId>();
  for (const drf of ER_MOVES) {
    const pkrgId = ER_ID_MAP.moves[drf.id];
    if (pkrgId !== undefined && pkrgId < 5000) {
      constToPkrgId.set(drf.moveConst, pkrgId as MoveId);
    }
  }

  // Build pokerogue MoveId → Move lookup.
  const byId = new Map<number, Move>();
  for (const move of allMoves) {
    // `allMoves` is sparse (custom moves are id-indexed ≥5000); skip the holes.
    if (move === undefined) {
      continue;
    }
    byId.set(move.id, move);
  }

  for (const [moveConst, override] of C_SOURCE_OVERRIDES) {
    const pkrgId = constToPkrgId.get(moveConst);
    if (pkrgId === undefined) {
      result.movesMissing++;
      continue;
    }
    const move = byId.get(pkrgId);
    if (!move) {
      result.movesMissing++;
      continue;
    }
    const target = move as {
      power: number;
      accuracy: number;
      pp: number;
      chance: number;
    };
    if (override.power !== undefined) {
      target.power = override.power;
    }
    if (override.accuracy !== undefined) {
      target.accuracy = override.accuracy;
    }
    if (override.pp !== undefined) {
      target.pp = override.pp;
    }
    if (override.chance !== undefined) {
      target.chance = override.chance;
    }
    result.movesPatched++;
  }

  // Apply flag patches: OR the missing flag bits into each move's flag mask.
  // Move.flags is private; we cast to access it.
  for (const [moveConst, flagBits] of C_SOURCE_FLAG_PATCHES) {
    const pkrgId = constToPkrgId.get(moveConst);
    if (pkrgId === undefined) {
      continue;
    }
    const move = byId.get(pkrgId);
    if (!move) {
      continue;
    }
    const target = move as unknown as { flags: number };
    target.flags = (target.flags ?? 0) | flagBits;
    result.flagsPatched++;
  }

  return result;
}
