//! Reward-shop and biome-market reducers for the selected M4 slice.
//!
//! Contract: `rust/contracts/m4-reward-market.md`. The two surfaces stay
//! distinct: the regular shop owns free selection, skip, paid purchase, reroll
//! and tier locks; the biome market owns stock quantity/sold state and leave
//! only — it never acquires reroll or lock actions. Every failure is a typed
//! rejection that mutates nothing and draws nothing.

use er_types::battle_ids::PokemonId;
use er_types::run_ids::{ModifierId, Money, RunOfferId, RunStockId};
use er_types::run_model::ModifierTier;

use crate::content::{MarketRuleSet, RewardRuleSet};
use crate::money;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ShopError {
    UnknownOffer,
    UnknownStock,
    OfferNotFree,
    PriceMismatch,
    AlreadySold,
    InsufficientMoney,
    StockDepleted,
    RerollUnsupported,
    LockUnsupported,
    LockCostUnpaid,
    OrdinalNotSequential,
    Money(money::MoneyError),
}

impl From<money::MoneyError> for ShopError {
    fn from(value: money::MoneyError) -> Self {
        Self::Money(value)
    }
}

fn debit_shop(balance: Money, amount: u64) -> Result<Money, ShopError> {
    match money::debit(balance, amount) {
        Ok(balance) => Ok(balance),
        Err(money::MoneyError::Underflow) => Err(ShopError::InsufficientMoney),
        Err(error) => Err(ShopError::Money(error)),
    }
}

/// One captured reward offer as generated by the authority.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RewardOfferView {
    pub offer_id: RunOfferId,
    pub modifier_id: ModifierId,
    pub tier: ModifierTier,
    pub price: Money,
    pub sold: bool,
}

/// Applies `SelectFree` / `Buy` payment validation for one offer.
///
/// Returns the post-payment balance. Marking the offer sold and applying the
/// modifier effect are caller-staged so this reducer stays pure over views.
pub fn pay_for_offer(
    balance: Money,
    offers: &[RewardOfferView],
    offer_id: RunOfferId,
    offered_price: Option<Money>,
) -> Result<Money, ShopError> {
    let offer = offers
        .iter()
        .find(|entry| entry.offer_id == offer_id)
        .ok_or(ShopError::UnknownOffer)?;
    if offer.sold {
        return Err(ShopError::AlreadySold);
    }
    match offered_price {
        None => {
            if offer.price != Money::ZERO {
                return Err(ShopError::OfferNotFree);
            }
            Ok(balance)
        }
        Some(price) => {
            if price != offer.price {
                return Err(ShopError::PriceMismatch);
            }
            debit_shop(balance, offer.price.get().get())
        }
    }
}

/// Applies a reroll payment under the regular shop's frozen base cost.
///
/// The oracle charges `base_cost * (count + 1)`; affordability is validated
/// before any draw. Returns the post-payment balance and the new count.
pub fn pay_for_reroll(
    balance: Money,
    rules: &RewardRuleSet,
    reroll_count: u32,
) -> Result<(Money, u32), ShopError> {
    if !rules.supports_reroll {
        return Err(ShopError::RerollUnsupported);
    }
    let cost = rules
        .reroll_base_cost
        .get()
        .get()
        .checked_mul(u64::from(reroll_count) + 1)
        .ok_or(ShopError::InsufficientMoney)?;
    let next = debit_shop(balance, cost)?;
    let count = reroll_count
        .checked_add(1)
        .ok_or(ShopError::InsufficientMoney)?;
    Ok((next, count))
}

/// Toggles one tier lock under the frozen per-tier schedule.
///
/// Requires an explicit lock-capability admission from the caller; a lock
/// toggle draws no RNG. `locking` selects paying the schedule cost (arm) vs
/// refund-free release (disarm). Returns the post-payment balance.
pub fn toggle_lock(
    balance: Money,
    rules: &RewardRuleSet,
    lock_capsule_present: bool,
    tier: ModifierTier,
    locking: bool,
) -> Result<Money, ShopError> {
    if !rules.supports_locks || !lock_capsule_present {
        return Err(ShopError::LockUnsupported);
    }
    if !locking {
        // Disarming a lock is free; the schedule is charged on arm only.
        return Ok(balance);
    }
    let index = usize::from(tier.get());
    let cost = rules
        .lock_cost_tiers
        .get(index)
        .ok_or(ShopError::LockCostUnpaid)?;
    debit_shop(balance, cost.get().get())
}

/// One biome-market stock entry view with quantity semantics.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct MarketStockView {
    pub stock_id: RunStockId,
    pub modifier_id: ModifierId,
    pub price: Money,
    pub initial_quantity: u16,
    pub remaining_quantity: u16,
    pub sold: bool,
}

impl MarketStockView {
    /// Sold state derives exactly from a depleted quantity.
    pub fn validate(&self) -> Result<(), ShopError> {
        let derived = self.remaining_quantity == 0;
        if self.initial_quantity == 0
            || self.remaining_quantity > self.initial_quantity
            || self.sold != derived
        {
            Err(ShopError::StockDepleted)
        } else {
            Ok(())
        }
    }
}

/// Applies a market buy: validates identity, price, remaining quantity and
/// affordability, then returns `(balance_after, updated_entry)`.
///
/// Quantity decrement and sold-state derivation are staged here; the modifier
/// application runs before the caller makes any of it visible.
pub fn buy_stock(
    balance: Money,
    stock: &[MarketStockView],
    stock_id: RunStockId,
    offered_price: Money,
) -> Result<(Money, MarketStockView), ShopError> {
    let entry = *stock
        .iter()
        .find(|entry| entry.stock_id == stock_id)
        .ok_or(ShopError::UnknownStock)?;
    entry.validate()?;
    if entry.sold || entry.remaining_quantity == 0 {
        return Err(ShopError::StockDepleted);
    }
    if offered_price != entry.price {
        return Err(ShopError::PriceMismatch);
    }
    let balance = debit_shop(balance, entry.price.get().get())?;
    let remaining = entry.remaining_quantity - 1;
    let updated = MarketStockView {
        remaining_quantity: remaining,
        sold: remaining == 0,
        ..entry
    };
    Ok((balance, updated))
}

/// Validates a leave action against the market rule set (always permitted;
/// present so every surface action is explicitly validated).
pub fn leave_market(rules: &MarketRuleSet) -> Result<(), ShopError> {
    if rules.supports_reroll || rules.supports_locks {
        // A market that acquired shop-only actions violates surface separation.
        Err(ShopError::LockUnsupported)
    } else {
        Ok(())
    }
}

/// Target evidence carried with paid purchases; kept as a type alias so
/// callers can name the stable Pokémon identity without extra imports.
pub type PurchaseTarget = PokemonId;

#[cfg(test)]
mod tests {
    use super::*;
    use er_types::SafeU53;

    fn id<T: From<SafeU53>>(value: u64) -> T {
        T::from(SafeU53::new(value).expect("id"))
    }

    fn money(value: u64) -> Money {
        Money::new(SafeU53::new(value).expect("money"))
    }

    fn rules() -> RewardRuleSet {
        RewardRuleSet {
            supports_reroll: true,
            supports_locks: true,
            reroll_base_cost: money(250),
            lock_cost_tiers: vec![money(50), money(125), money(300), money(750), money(2000)],
            selected_modifier_keys: Vec::new(),
        }
    }

    fn offer(free: bool) -> RewardOfferView {
        RewardOfferView {
            offer_id: id(1),
            modifier_id: id(7),
            tier: ModifierTier::Common,
            price: if free { money(0) } else { money(300) },
            sold: false,
        }
    }

    #[test]
    fn free_select_requires_a_zero_price_offer() {
        let free = offer(true);
        assert_eq!(
            pay_for_offer(money(10), std::slice::from_ref(&free), free.offer_id, None),
            Ok(money(10))
        );
        assert_eq!(
            pay_for_offer(
                money(10),
                std::slice::from_ref(&free),
                free.offer_id,
                Some(money(0))
            ),
            Ok(money(10))
        );
        let paid = offer(false);
        assert_eq!(
            pay_for_offer(money(10), std::slice::from_ref(&paid), paid.offer_id, None),
            Err(ShopError::OfferNotFree)
        );
    }

    #[test]
    fn buy_charges_the_exact_listed_price() {
        let paid = offer(false);
        assert_eq!(
            pay_for_offer(
                money(1_000),
                std::slice::from_ref(&paid),
                paid.offer_id,
                Some(money(300))
            ),
            Ok(money(700))
        );
        assert_eq!(
            pay_for_offer(
                money(1_000),
                std::slice::from_ref(&paid),
                paid.offer_id,
                Some(money(299))
            ),
            Err(ShopError::PriceMismatch)
        );
        assert_eq!(
            pay_for_offer(
                money(299),
                std::slice::from_ref(&paid),
                paid.offer_id,
                Some(money(300))
            ),
            Err(ShopError::InsufficientMoney)
        );
    }

    #[test]
    fn reroll_costs_escalate_and_require_funds() {
        let (balance, count) = pay_for_reroll(money(1_000), &rules(), 0).expect("reroll 1");
        assert_eq!(balance.get().get(), 750);
        assert_eq!(count, 1);
        let (_, count2) = pay_for_reroll(balance, &rules(), count).expect("reroll 2");
        assert_eq!(count2, 2);
        assert_eq!(
            pay_for_reroll(money(100), &rules(), 0),
            Err(ShopError::InsufficientMoney)
        );
    }

    #[test]
    fn lock_arm_pays_schedule_disarm_is_free() {
        let armed =
            toggle_lock(money(1_000), &rules(), true, ModifierTier::Great, true).expect("arm");
        assert_eq!(armed.get().get(), 875);
        assert_eq!(
            toggle_lock(armed, &rules(), true, ModifierTier::Great, false).expect("disarm"),
            armed
        );
        assert_eq!(
            toggle_lock(money(1_000), &rules(), false, ModifierTier::Common, true),
            Err(ShopError::LockUnsupported)
        );
    }

    #[test]
    fn market_buy_decrements_and_derives_sold() {
        let stock = MarketStockView {
            stock_id: id(9),
            modifier_id: id(400),
            price: money(60),
            initial_quantity: 2,
            remaining_quantity: 2,
            sold: false,
        };
        let (balance, updated) = buy_stock(
            money(500),
            std::slice::from_ref(&stock),
            stock.stock_id,
            money(60),
        )
        .expect("buy");
        assert_eq!(balance.get().get(), 440);
        assert_eq!(updated.remaining_quantity, 1);
        assert!(!updated.sold);
        let (_, final_entry) = buy_stock(
            balance,
            std::slice::from_ref(&updated),
            stock.stock_id,
            money(60),
        )
        .expect("buy 2");
        assert!(final_entry.sold);
        assert_eq!(
            buy_stock(
                balance,
                std::slice::from_ref(&final_entry),
                stock.stock_id,
                money(60)
            ),
            Err(ShopError::StockDepleted)
        );
    }

    #[test]
    fn market_leave_rejects_shop_contaminated_rules() {
        let clean = MarketRuleSet {
            supports_reroll: false,
            supports_locks: false,
            maximum_stock_entries: 16,
            selected_modifier_keys: Vec::new(),
        };
        assert_eq!(leave_market(&clean), Ok(()));
    }
}
